// --- DATA: Chronologically Ordered Sets (Extracted from ca audit set.html) ---
const quizSets = [
    {
        setName: "Set 1",
        questions: [
            { q: "1. Which of the following is/are not characteristic of a company?", o: ["It is a distinct legal entity existing independent of its members.", "It has a perpetual succession.", "The shares of a company are freely transferable except in case of a Private limited Company.", "It is a voluntary association of persons usually for social up liftment without expectation of any profit."], c: "It is a voluntary association of persons usually for social up liftment without expectation of any profit." },
            { q: "2. Which of the following is/are the important feature/s of a company?", o: ["Accounting process is highly regulated and guided by regulatory pronouncements", "Constituents of periodical accounts (i.e., income statement, balance sheet etc.) are specified by the law", "Importance of compliance to the prescribed rules and regulations is paramount", "All of these"], c: "All of these" },
            { q: "3. In India, accounting in of a company form is guided by which of the following regulatory sources?", o: ["Companies Act, 2013", "Company Rules", "Accounting Standards", "All of these"], c: "All of these" },
            { q: "4. Which of the following is not a statutory book of a company?", o: ["Register of Investments held and their names", "Annual returns", "Register of Officers", "Register of shareholdings of the directors"], c: "Register of shareholdings of the directors" },
            { q: "5. Which of the following is/are not a feature/s of Shares have the following features?", o: ["It represents the biggest unit of ownership", "Shares of a specific series must have the same face value", "Share represents only a partial ownership of Share Capital of the company", "Each share has a distinct number"], c: "It represents the biggest unit of ownership" },
            { q: "6. In case of ____ issue the shares are offered to the existing shareholders of the company without any consideration.", o: ["Private Placement", "Rights Issue", "Bonus Issue", "Offers for sale"], c: "Bonus Issue" },
            { q: "7. When share is issued at a price equal to its face value, it is called issue", o: ["at Par", "Issue at a Premium", "Issue at a Discount", "at Bonus"], c: "at Par" },
            { q: "8. Provisions relating to buy back of securities are contained in ____ of the Companies Act, 2013.", o: ["Section 77", "Section 77A", "Section 68", "Section 63"], c: "Section 68" },
            { q: "9. Buy-back of equity shares in any financial year should not exceed", o: ["10% of net worth", "25% of the aggregate of paid-up capital and free reserves of the company", "25% of the paid-up equity capital", "25% of the aggregate of paid-up equity capital and preference capital"], c: "25% of the aggregate of paid-up capital and free reserves of the company" },
            { q: "10. Company may purchase its own shares or other specified securities out of- A. Free reserves, B. Securities premium account, C. Proceeds of issue of any shares, D. Proceeds of issue of specified securities", o: ["A and C only", "A. b and C only", "A, C and D only", "A or B or C or D"], c: "A or B or C or D" },
            { q: "11. Section 68 of the Companies Act, 2013 provides that no buy-back of any kind of shares or other specified securities shall be made out of the", o: ["Securities premium balance as it stood before buy back", "Proceeds of an earlier issue of the same kind of shares or same kind of other specified securities", "General reserve in excess of 15% balance as per latest audited balance sheet", "Proceeds of issue of specified securities"], c: "Proceeds of an earlier issue of the same kind of shares or same kind of other specified securities" },
            { q: "12. For the purpose of calculating debt equity ratio which of the following debts are considered", o: ["Secured debts", "Unsecured debts", "Current liabilities", "All of the above"], c: "All of the above" },
            { q: "13. Where a company purchase its own shares out of free reserves or securities premium account, a sum equal to the nominal value of the shares so purchased shall be transferred to the", o: ["Capital Reserve Account", "General Reserve Account", "Capital Redemption Reserve Account", "Equity Shares Redemption Account"], c: "Capital Redemption Reserve Account" },
            { q: "14. No offer of buy-back shall be made within a period of ____ reckoned from the date of the closure of the preceding offer of buy-back", o: ["6 months", "1 year", "2 years", "10 months"], c: "1 year" },
            { q: "15. Equity shares amounting to Rs.2,00,000 are brought back at a premium of 5%, by issue of preference shares amounting to Rs.1,00,000 at a premium of 10%. Compute the amount to be transferred to Capital Redemption Reserve.", o: ["Rs.1,00,000", "Rs.90,000", "Rs. 1,50,000", "Rs.50,000"], c: "Rs.1,00,000" }
        ]
    },
    {
        setName: "Set 2",
        questions: [
            { q: "16. Following are the extract of balance sheet of Light Co. Ltd. Equity share of Rs. 10 each - Rs.10,00,000, Security Premium - Rs.2,40,000, Reserve- Rs.7,50,000, Profit & Loss Account - Rs.2,80,000, Bank - Rs.9,10,000, Non Trading Investments- Rs.4,20,000. Company brought back 15,000 shares at Rs.40 each. The transaction in respect of buy back was financed by sale of 2/3rd of non-trade investment for Rs.5,90,000. Amount to be transferred to capital redemption reserve is", o: ["Rs.6,00,000", "Rs.1,00,000", "Rs.4,50,000", "Rs.1,50,000"], c: "Rs.1,50,000" },
            { q: "17. Following information is available from the audited balance sheet of TH Ltd.: Equity Shares Capital (3,000 lakh share of Rs.10 each) - Rs.30,000, Securities Premium Account - Rs.3,000, General Reserve - Rs. 10,000, Secured Loans - Rs.40,000, Unsecured Loans - Rs.22,000. Compute the maximum limits up to which buy back is permitted in the financial year 2022-23.", o: ["800 lakh shares", "1075 lakh shares", "500 lakh shares", "400 lakh shares"], c: "1075 lakh shares" },
            { q: "18. The notice of the meeting at which the special resolution is proposed to be passed relating to buy back of shares shall be accompanied by an explanatory statement stating", o: ["Full and complete disclosure of all material facts", "Analysis of debt equity", "Gross profit ratio before buy back", "Chairman's view on buy back"], c: "Full and complete disclosure of all material facts" },
            { q: "19. The balance appearing in the books of a company at the end of year were: CRR A/c Rs. 50,000, Securities Premium Rs. 5,000, Revaluation Reserve Rs. 20,000, Profit & Loss A/c (Dr.) Rs. 10,000. Maximum amount available for bonus shares will be", o: ["Rs.50,000", "Rs.55,000", "Rs.45,000", "Rs.57,000"], c: "Rs.55,000" },
            { q: "20. ____ is the amount of share capital that a company is permitted to issue.", o: ["Issued Share Capital", "Authorized Share Capital", "Subscribed Capital", "Paid up Capital"], c: "Authorized Share Capital" },
            { q: "21. When shares are forfeited, the share capital account is debited with", o: ["Called-up value of shares", "Nominal value of shares", "Market value of shares", "Paid-up value of shares"], c: "Called-up value of shares" },
            { q: "22. Forfeiture of shares results in the reduction of", o: ["Authorised capital", "Reserve capital", "Paid-up capital", "Fixed assets"], c: "Paid-up capital" },
            { q: "23. Shares can be forfeited", o: ["For failure to attend meetings", "For failure to repay the loan to the bank", "For non-payment of call money", "For which shares are pledged as a security"], c: "For non-payment of call money" },
            { q: "24. Redeemable Preference Shares of Rs. 1,00,000 are redeemed at a premium of 5% for which purpose fresh equity capital of Rs. 40,000 is issued at par. What amount should be transferred to Capital Redemption Reserve account?", o: ["Rs.40,000", "Rs. 1,05,000", "Rs.65,000", "Rs.60,000"], c: "Rs.60,000" },
            { q: "25. The financial statements of company shall be in the from provided in", o: ["Schedule IV", "Schedule III", "Schedule V", "Schedule VI"], c: "Schedule III" },
            { q: "26. Part I of the Schedule III to the Companies Act, 2013 gives the", o: ["Format of Profit & Loss Account", "General instructions for preparation of Profit & Loss Account", "Format of Balance Sheet", "Format of Comparative Statements"], c: "Format of Balance Sheet" },
            { q: "27. Where the company covered under section 135 of the Companies Act, 2013, which of the following shall be disclosed with regard to CSR activities?", o: ["amount of expenditure incurred", "shortfall at the end of the year", "shortfall at the end of the year", "All of these"], c: "All of these" },
            { q: "28. Which of the following is/are not a criteria to classify a liability as current liability?", o: ["it is expected to be settled in the company's normal operating cycle", "it is held primarily not for the purpose of being traded", "it is due to be settled within twelve months after the reporting date", "the company does not have an unconditional right to defer settlement of the liability for at least twelve months after the reporting date"], c: "it is held primarily not for the purpose of being traded" },
            { q: "29. What are the major types of financial statements prepared by entities?", o: ["(a) Statement of Financial Performance or Income Statement, (b) Statement of Financial State of Affairs or Balance Sheet, (c) Statement of Changes in Financial Position, (d) Statement of Inflow and Outflow of Cash", "(a) Statement of Trial Balance, (b) Statement of Financial State of Affairs or Balance Sheet, (c) Statement of Changes in Financial Position, (d) Statement of Inflow and Outflow of Cash", "(a) Statement of Financial Performance or Income Statement, (b) Statement of Financial State of Affairs or Balance Sheet, (c) Statement of Changes in Financial Position, (d) Statement of Fund Flows", "(a) Statement of Financial Performance or Income Statement, (b) Statement of Financial State of Affairs or Balance Sheet, (c) Statement of Changes in Financial Position, (d) Cash Book"], c: "(a) Statement of Financial Performance or Income Statement, (b) Statement of Financial State of Affairs or Balance Sheet, (c) Statement of Changes in Financial Position, (d) Statement of Inflow and Outflow of Cash" },
            { q: "30. If the turnover of the company is less than Rs. 100 Crore, the figures appearing in the Financial Statements shall be rounded off to nearest -", o: ["To the nearest hundreds", "To the nearest hundreds and thousands", "To the nearest hundred, thousands, lakh or million thereof", "To the nearest hundreds, thousands, lakhs or millions, or decimals thereof"], c: "To the nearest hundreds, thousands, lakhs or millions, or decimals thereof" }
        ]
    },
    {
        setName: "Set 3",
        questions: [
            { q: "31. Under which heading the Deferred Tax Liabilities appears in the balance sheet", o: ["Current Liabilities", "Non-Current Liabilities", "Deferred Liabilities", "Contingent Liabilities"], c: "Non-Current Liabilities" },
            { q: "32. As asset shall be classified as current", o: ["If it is held primarily for the purpose of being traded.", "If it is not possible to classify such asset as non-current asset", "It or the asset normal operating cycle cannot be identified", "All of the above"], c: "If it is held primarily for the purpose of being traded." },
            { q: "33. A liability shall be classified as current when it satisfies any of the following criteria:", o: ["It is expected to be settled in the Company's normal operating cycle", "It is due to be settled within twelve months after the reporting date", "The company does not have an unconditional right to defer settlement of the liability of at least twelve months after the reporting date.", "Any of the above"], c: "Any of the above" },
            { q: "34. Which of the following appears under the heading 'Reserve & Surplus' in the balance sheet", o: ["Share Options Outstanding Account", "Share Application Money Pending Allotment", "Long Term Provisions", "Share Application Money due for refund"], c: "Share Options Outstanding Account" },
            { q: "35. In the Balance Sheet Bank Overdraft will be shown as a liability under the heading -", o: ["Other Current Liabilities", "Short Term Borrowings", "Current Liabilities", "Cash & Cash Equivalent"], c: "Short Term Borrowings" },
            { q: "36. In the Balance Sheet Calls in Arrears will be shown in -", o: ["Liabilities Side", "Assets Side", "Assets or Liabilities Side", "Liabilities"], c: "Liabilities Side" },
            { q: "37. Futura Ltd had the following items under the head \"Reserves and Surplus\" in the Balance Sheet as on 31st March: (Rs. in Lakhs) Securities Premium Account - 80, Capital Reserve - 60, General Reserve - 90. The Company had an Accumulated Loss of Rs. 250 Lakhs on the same date. Reserves & Surplus to be disclosed in B/S is", o: ["Rs.250 Lakhs", "Rs.230 Lakhs", "Rs.20 Lakhs", "Rs.(20 Lakhs)"], c: "Rs.(20 Lakhs)" },
            { q: "38. In the Notes to Accounts a Contingent liabilities shall be classified as", o: ["Claims against the company not acknowledged as debt", "Guarantees", "Other money for which the company is contingently liable", "All of these"], c: "All of these" },
            { q: "39. In case of purchase of assets under instalment payment system, instalments due after 12 months from the reporting date are shown as", o: ["Current liability", "Current assets", "Non-current liability", "Non-current assets"], c: "Non-current liability" },
            { q: "40. As per Schedule III of Companies Act 2013, while preparing the financial statements in case of a Finance Company, interest received from borrowers should be shown under", o: ["Revenue from operation", "Other Income", "Current assets", "Non-current assets"], c: "Revenue from operation" },
            { q: "41. Inventories are valued at the lower of ____ or the net realizable value.", o: ["Fair Value", "Historical cost", "Current value", "None of these"], c: "Historical cost" },
            { q: "42. The amount of Calls-in-Advance not yet adjusted till the Balance Sheet date is shown under ____ under the head Current Liabilities", o: ["Other Current Liabilities", "Inventories", "Trade Receivables", "Trade Paybles"], c: "Other Current Liabilities" },
            { q: "43. Proposed Dividend is treated as a ____ and is shown as a deduction in Reserve and Surplus.", o: ["Contingent Liabilities", "Current Assets", "Current Liabilities", "None of these"], c: "Contingent Liabilities" },
            { q: "44. Cash receipts from disposal of shares is classified under", o: ["Investing Activity", "Operating Activity", "Financing Activity", "Cash Equivalent"], c: "Investing Activity" },
            { q: "45. The main difference in direct and indirect method is to calculate the", o: ["Cash Flows from Investing Activity", "Cash Flows from Operating Activity", "Cash Flows from Financing Activity", "All of these"], c: "Cash Flows from Operating Activity" }
        ]
    },
    {
        setName: "Set 4",
        questions: [
            { q: "46. What is/are objective/s of preparing Cash Flow Statement?", o: ["to determine ability of the entity to generate cash and cash equivalents", "to meet the needs of the entity to utilise the cash flows", "to ascertain gross inflows and outflows of cash", "All of these"], c: "All of these" },
            { q: "47. When company repurchases its own shares it records a", o: ["Cash inflow", "Cash outflow", "No effect on cash", "None of these"], c: "Cash outflow" },
            { q: "48. A Cash Flow Statement begins with", o: ["Investing Activity", "Operating Activity", "Financing Activity", "Cash Equivalent"], c: "Operating Activity" },
            { q: "49. Which of the following item is not considered as Cash Equivalent?", o: ["Short term deposits in Banks", "Short term deposits in Banks", "Bill Receivables", "Commercial Papers"], c: "Bill Receivables" },
            { q: "50. Which of the following is an example of Non-cash Expenses", o: ["Depreciation", "Wages and Salaries", "Payment of Dividend", "All of these"], c: "Depreciation" },
            { q: "51. If the Net Operating Profit is Rs. 90,000 and the Debtors are decreased by Rs. 20,000 during the year. Then Cash from Operation will be", o: ["Rs.70,000", "Rs.1,10,000", "Rs.90,000", "None of these"], c: "Rs.1,10,000" },
            { q: "52. Increase of Bills Receivable by Rs. 30,000 results in", o: ["Decrease in Cash", "Increase in Cash", "No effect on cash", "All of these"], c: "Decrease in Cash" },
            { q: "53. Marketable securities are treated as ____ in Cash Flow Statement", o: ["Cash", "Cash equivalent", "Current Asset", "Non-cash Equivalent"], c: "Cash equivalent" },
            { q: "54. An example of Cash Flow from Financing Activity is", o: ["Payment of Dividend", "Receipt of dividend on investment", "Cash received from customer", "Purchase of Fixed Assets"], c: "Payment of Dividend" },
            { q: "55. Which of the following is a source of Cash?", o: ["Cash deposited into Bank", "Cash withdrawn from Bank", "Sale of Goods Costing Rs. 20,000 Rs. 15,000", "Depereciation charged on Fixed Assets"], c: "Sale of Goods Costing Rs. 20,000 Rs. 15,000" },
            { q: "56. Interest on Long term borrowing is an expense relating to", o: ["Investing Activity", "Operating Activity", "Financing Activity", "All of these"], c: "Financing Activity" },
            { q: "57. A company received dividend of Rs. 1,00,000 on its investment in other company's share. In case of a Finance company it will be classified as", o: ["Cash Flows from Investing Activity", "Cash Flows from Operating Activity", "Cash Flows from Financing Activity", "None of these"], c: "Cash Flows from Operating Activity" },
            { q: "58. Advance received from customers is classified as", o: ["Cash Flows from Investing Activity", "Cash Flows from Operating Activity", "Cash Flows from Financing Activity", "None of these"], c: "Cash Flows from Operating Activity" },
            { q: "59. Acquired the assets of a company through issue of equity shares is classified as", o: ["Cash Flows from Investing Activity", "Cash Flows from Operating Activity", "Cash Flows from Financing Activity", "None of these"], c: "None of these" },
            { q: "60. A Ltd. paid an advance tax amounting to Rs. 3,65,000 out of which Rs. 15,000 is relating to a short-term capital gain on sale of securities. How will A Ltd. report the payment of advance tax in its Cash Flow Statement?", o: ["Cash Flows from Operating Activity", "Cash Flows from Investing Activity", "Cash Flows from Financing Activity", "None of these"], c: "Cash Flows from Operating Activity" }
        ]
    },
    {
        setName: "Set 5",
        questions: [
            { q: "61. Cash flows from operating activities (Rs. 550) Lakhs, Cash flows from investment activities (Rs. 1,250) Lakhs, Cash flows from financing activities Rs. 1,750 Lakhs. Determine the changes in cash and cash equivalents is", o: ["Decrease in Cash and Cash Equivalent by Rs. 50 Lakhs", "Increase in Cash and Cash Equivalent by Rs. 50 Lakhs", "No change in Cash and Cash Equivalent", "It is a non Cash item"], c: "Decrease in Cash and Cash Equivalent by Rs. 50 Lakhs" },
            { q: "62. The method for presenting Net cash provided by operating activities that starts with net income and adjusts it for items that affected reported net income but that did not affect cash is called as", o: ["Direct method", "Working capital method", "Indirect method", "Cost-benefit method"], c: "Indirect method" },
            { q: "63. X Ltd. purchased machinery of Rs. 10,00,000 issuing a cheque of Rs. 2,50,000 and 10% Debentures of Rs. 7,50,000. In the cash flow statement, the transaction will be shown as", o: ["Outflow under investing activity Rs. 10,00,000, inflow under financing activity as receipt for debentures Rs. 7,50,000", "Outflow under investing activity Rs. 2,50,000", "Inflow of Rs. 7,50,000 as financing activity.", "None of the above"], c: "Outflow under investing activity Rs. 2,50,000" },
            { q: "64. From the following information presented by P Ltd, ascertain the Net Realisable Value of stock: Cost Price of certain stock amounted to Rs. 60,000; being obsolete, it can be used for production purposes after incurring Rs. 10,000 for modification. The same could be used as a raw material for an existing product, the purchase price for the same amounts to Rs. 40,000.", o: ["Rs.60,000", "Rs.40,000", "Rs.30,000", "Rs. 10,000"], c: "Rs.40,000" },
            { q: "65. Objectives of Bank's Book keeping system is/are", o: ["to keep up-to-date detailed ledgers", "to balance the trial balance every day", "to keep all control accounts in agreement with the detailed ledgers", "All of these"], c: "All of these" },
            { q: "66. Which of the following is/are not Subsidiary Register of a banking company?", o: ["Demand Drafts, Telegraphic Transfers and Mail Transfers issued on Branches and Agencies", "Demand Drafts, Telegraphic Transfers and Mail Transfers received from Branches and Agencies", "Letters of Indemnity", "Letters of Credit"], c: "Letters of Indemnity" },
            { q: "67. Some of the common purposes are of a Bank's Statistical Books is/are", o: ["To record Average Balance in Loan and Advances etc.", "To record Deposits received and amount paid out each month in the various departments", "To record Average Balance of Assets", "Both 1 and 2"], c: "Both 1 and 2" },
            { q: "68. Amount of Bill x Rate of Discount x Unexpired period (in months)/12", o: ["Rebate on Bills Discounted", "Discount on Bills", "Interest", "Loan Amount"], c: "Rebate on Bills Discounted" },
            { q: "69. The status of securities and the value of such securities must be mentioned by every bank in Schedule", o: ["2", "4", "7", "9"], c: "9" },
            { q: "70. The Electricity Act, 2003 replaced which of the following erstwhile existing legislations?", o: ["The Indian Electricity Act, 1910", "The Electricity (Supply) Act, 1948", "The Electricity Regulatory Commissions Act, 1998", "All of these"], c: "All of these" },
            { q: "71. Which of the following is/are main feature of Electricity Act, 2003?", o: ["The activities like generation, transmission and distribution of power have been separately identified.", "Power generation has partially been de-licensed", "20% of the power supplied by suppliers and distributors to the consumers has to be generated using renewable and non-conventional sources of energy", "Metering of all electricity supplied has been made optional"], c: "The activities like generation, transmission and distribution of power have been separately identified." },
            { q: "72. The Central Commission shall consist of which of the following Members?", o: ["A chairperson and 3 Members", "The Chairperson of the Authority who shall be the Member, ex-officio.", "Both 1 and 2", "None of them"], c: "Both 1 and 2" },
            { q: "73. Rate of provisioning for advances doubtful for more than 1 year but less than 3 years is", o: ["25%", "40%", "60%", "100%"], c: "40%" },
            { q: "74. Which of the following is a principle of insurance?", o: ["Principle of indemnity", "Insurable interest.", "Principle of uberrimae fidei.", "All of the above"], c: "All of the above" },
            { q: "75. Rate of provision on advances doubtful for more than 3 years IS", o: ["40%", "25%", "100%", "Nil"], c: "100%" }
        ]
    },
    {
        setName: "Set 6",
        questions: [
            { q: "76. Which of the following is not a mandatory financial statement of a General Insurance Company as per IRDA regulations?", o: ["Revenue Account", "Profit and Loss Account", "Balance Sheet", "Cash Flow Statement"], c: "Cash Flow Statement" },
            { q: "77. Premia collected For Marine Insurance: (a) Insured (other than insurance companies) in respect of policies issued is Rs. 45 Cr. (b) Other insurance companies in respect of risks undertaken is Rs. 17.5 Cr. (c) Premia paid/payable to other insurance companies on business ceded is Rs. 16.75 Cr. Compute the closing balance in Unexpired Risks Reserve Account.", o: ["Rs.45 Cr.", "Rs.45.75 Cr.", "Rs. 12.50 Cr.", "Rs.8.25 Cr."], c: "Rs.45.75 Cr." },
            { q: "78. ____ is a reserve which should be created by the insurers towards losses which might arise due to entirely unexpected set of events and not for any specific known purpose.", o: ["General Reserve", "Catastrophe Reserve", "Revenue Reserve", "Surplus"], c: "Catastrophe Reserve" },
            { q: "79. Date of bill 15.01.2023, Period 5 months, Rate of discount 8%. Calculate rebate on bill discounted, if accounting year ends on 31.03.23.", o: ["Rs.852.46", "Rs.818.85", "Rs.873.22", "Rs.825.45"], c: "Rs.852.46" },
            { q: "80. Information provided by General Purpose Financial Reporting are as follows", o: ["Economic resources i.e., assets", "Claims against the entity i.e., liabilities", "Changes in economic resources and claims", "All of these"], c: "All of these" },
            { q: "81. Which of the following does not encompass Enhancing Qualitative Characteristics", o: ["Comparability", "Verifiability", "Uniformity", "Understandability"], c: "Uniformity" },
            { q: "82. ____ measures provide monetary information about assets, liabilities and related income and expenses, using information updated to reflect conditions at the measurement date.", o: ["Historical Cost", "Current Value", "Notional Value", "Net Realisable Value"], c: "Current Value" },
            { q: "83. A complete set of financial statements comprises which of the following?", o: ["a balance sheet as at the end of the period", "Statement of changes in equity for the period", "Both 1 and 2", "a statement of fund flows for the period"], c: "Both 1 and 2" },
            { q: "84. From the following information presented by P Ltd, ascertain the Net Realisable Value of stock: Cost Price of certain stock amounted to Rs. 60,000; being obsolete, it can be used for production purposes after incurring Rs. 10,000 for modification. The same could be used as a raw material for an existing product, the purchase price for the same amounts to Rs. 40,000.", o: ["Rs.60,000", "Rs.40,000", "Rs.30,000", "Rs. 10,000"], c: "Rs.30,000" },
            { q: "85. Z Co. Ltd. purchased goods at the cost of Rs. 40 lakhs in October 2021. Till March 2022, 75% of the stocks were sold. The company wants to disclose closing stock at Rs. 10 lakhs. The expected sales value is Rs. 11 lakhs and a commission at 10% on sale is payable to the agent. What is the correct closing stock value to be disclosed as at 31.3.2022?", o: ["Rs.11,0,000", "Rs.9,90,000", "Rs. 10,00,000", "Rs.40,00,000"], c: "Rs.9,90,000" },
            { q: "86. Mr. X is an employee of ABC Ltd. His annual salary is Rs. 15 lakh. The company follows a 300 working days policy. As per the policy of the company, Mr. X is entitled to a leave of 10 days for 2022-23. He, however, utilises 8 days leave. The unutilised leaves are not allowed to be carried forward but are settled by way of payment to the employee. Compute the amount to be paid for unutilised leaves.", o: ["Rs.5,000", "Rs. 10,000", "Rs. 15,00,000", "Rs.1,50,000"], c: "Rs. 10,000" },
            { q: "87. 01.04.2022 B Ltd. has 3600 ordinary shares outstanding. On 31.08.2023 it issued 1200 ordinary shares for cash. On 31.01.23 it bought back 600 ordinary shares. Calculate weighted average number of shares as on 31.03.23.", o: ["4200 shares", "4800 shares", "3600 shares", "1200 shares"], c: "4200 shares" },
            { q: "88. C Ltd. had 10,00,000 ordinary shares outstanding as on 01.04.2022. On 01.01.2023 it issued 2 ordinary shores bonus for each shore outstanding on 31.12.2022. Profit for the year 2021-22 was Rs. 9,00,000. Profit for 2022-23 was Rs. 30,00,000. Calculate the adjusted EPS for the year 2021-22.", o: ["Rs.1.00", "Rs.0.30", "Rs.3.00", "Rs.3.33"], c: "Rs.0.30" },
            { q: "89. An entity has an obligation to restore an asset for the damage it has in the past. It has Rs. 20 lakh cash to pay on 31.03.2022 relating to this liability. The entity considers that 15% is an appropriate discount rate, the time value of money is considered material. Calculate the amount to be provided.", o: ["Rs. 15.12 lakh", "Rs.20 lakh", "Rs.3.00 lakh", "None of these"], c: "Rs. 15.12 lakh" },
            { q: "90. Ind AS 1 \"Presentation of financial statements\" applies to", o: ["Consolidated financial statements in accordance with Ind AS 110, Consolidated Financial Statements,", "Separate financial statements in accordance with Ind AS 27, Separate Financial Statements.", "Both of the above", "All of these"], c: "Both of the above" }
        ]
    },
    {
        setName: "Set 7",
        questions: [
            { q: "91. Which of the following is not a part of other long-term benefits?", o: ["Long-term disability benefits", "Retirement benefits", "Profit-sharing and bonuses", "Deferred remuneration"], c: "Retirement benefits" },
            { q: "92. Ind AS 2, Inventories, does not apply to", o: ["Financial Instruments", "Biological Assets", "Both 1 and 2", "1 but not 2"], c: "Both 1 and 2" },
            { q: "93. Which of the following is a defined contribution plan?", o: ["Multi-employer plan", "State plan", "Insured benefits", "All of the above"], c: "All of the above" },
            { q: "94. Ordinary shares are Rs. 1,00,000 of Rs. 1.00; 10% Preference shares are Rs. 200,000 of Rs. 1.00; PAT Rs. 10,00,000. Calculate basic EPS.", o: ["Rs.9.80", "Rs.9.60", "Rs.9.40", "Rs.9.20"], c: "Rs.9.80" },
            { q: "95. The expected sales value of stock is Rs. 20 lakhs and a commission at 10% on sale is payable to the agent. Calculate NRV.", o: ["Rs.12 lakh", "Rs. 14 lakh", "Rs.16 lakh", "Rs.18 lakh"], c: "Rs.18 lakh" },
            { q: "96. The method for presenting Net cash provided by operating activities that starts with net income and adjusts it for items that affected reported net income but that did not affect cash is called as.", o: ["Direct method", "Working capital method", "Indirect method", "Cost-benefit method"], c: "Indirect method" },
            { q: "97. Given salary expenses Rs. 40,000, Outstanding in the beginning of the year Rs. 5,000 and outstanding at the end of the year Rs. 10,000. Cash outflow on salary will be.", o: ["Rs.55,000", "Rs.45,000", "Rs.35,000", "Rs.15,000"], c: "Rs.35,000" },
            { q: "98. Which of the following is outside the scope of Ind AS 1?", o: ["Financial Review by Management", "Environmental Reports", "Value Added Statements", "All of these"], c: "All of these" },
            { q: "99. Which of the following is included in cost of inventory as per Ind AS 2?", o: ["Duties and taxes subsequently recoverable from taxing authorities", "Freight inward", "Rebates", "Duty drawbacks"], c: "Freight inward" },
            { q: "100. Y Ltd. supplied the following information: Net Profit for 2021-22 Rs. 10,00,000. Net Profit for 2022-23 Rs. 15,00,000. No. of shares prior to right issue = 5,00,000. Terms of right issue: 1 new share for every 4 shares held; right issue price Rs. 20. Fair value of 1 ordinary share immediately prior to exercise of right = Rs. 25. Compute the Right Factor", o: ["2.5", "1.92", "1.04", "2.00"], c: "1.04" },
            { q: "101. ____ is the price that would be received to sell an asset, or paid to transfer a liability, in an orderly transaction between market participants at the measurement date.", o: ["Fair Value", "Value in use", "Current Cost", "Net Realisable Value"], c: "Fair Value" },
            { q: "102. Which of the following is included in cost of inventory as per IND AS 2?", o: ["Duties and Taxes subsequently recoverable from taxing authorities", "Freight inwards", "Rebates", "Duty drawbacks"], c: "Freight inwards" },
            { q: "103. Events occurring after the Reporting Period are those events that occur between ---", o: ["reporting date and issue date", "reporting date and approval date", "finalisation date and approval date", "finalisation date and issue date"], c: "reporting date and approval date" },
            { q: "104. How many types of Employee Benefits are there as per Ind AS 19?", o: ["1", "2", "3", "4"], c: "4" },
            { q: "105. Which of the following is not an essential features of auditing?", o: ["It involves evaluation & verification of the relevance, reliability and adequacy of evidence in support of verifiable information such as vouchers, documents, explanations.", "It is analytical, critical and investigative review of systems of Accounting & Internal Controls.", "The information audited are non-financial in nature.", "There should be standards or criteria for evaluation of the information in a systematic & scientific manner."], c: "The information audited are non-financial in nature." }
        ]
    },
    {
        setName: "Set 8",
        questions: [
            { q: "106. The word \"Auditing\" has been derived from Latin word \"audiere\" which means", o: ["To Hear", "To verify", "To Examine", "To Identify"], c: "To Hear" },
            { q: "107. Management is interested in the Financial Statements for", o: ["For day-to-day decision-making", "For Collection of Taxes", "For research purpose", "None of the above"], c: "For day-to-day decision-making" },
            { q: "108. Government is interested in the Financial Statements for", o: ["For day-to-day decision-making", "For Collection of Taxes", "For research purpose", "None of the above"], c: "For Collection of Taxes" },
            { q: "109. Verification of the value of assets, liabilities, and the balance of reserves, provision and the amount of profit earned or loss suffered by an entity is called as", o: ["Continuous audit", "Balance sheet audit", "Interim audit", "Partial audit"], c: "Balance sheet audit" },
            { q: "110. Audit in depth synonymous for", o: ["Examination in Depth", "Completed audit", "Final audit", "Internal audit"], c: "Examination in Depth" },
            { q: "111. Test Checking reduces the", o: ["Power of an auditor", "Expenses of auditor", "Work of an auditor", "Liability of an auditor"], c: "Work of an auditor" },
            { q: "112. A flow chart, made by the auditor, of an entity's internal control system is a graphic representation that depicts the auditor's", o: ["Understanding of the system", "Understanding of fraud risk factors", "Documentation of assessment of control risk", "Both 1 and 3"], c: "Understanding of the system" },
            { q: "113. Internal auditor is appointed by", o: ["The Management", "The Shareholders", "The Government", "The Statutory Body"], c: "The Management" },
            { q: "114. The work of one clerk is automatically check by another clerk is called", o: ["Internal control", "Internal check", "Internal audit", "None of the above"], c: "Internal check" },
            { q: "115. An internal control includes", o: ["Internal Audit", "Internal Check", "Both I and 2", "None of the above"], c: "Both I and 2" },
            { q: "116. The most important objective of internal audit is", o: ["Early detection of errors and fraud", "Facilitating final audit", "Early finalization of annual account", "Ensuring systematic accounting"], c: "Early detection of errors and fraud" },
            { q: "117. Internal check is meant for", o: ["Prevention of frauds", "Detection of frauds", "Helping audit is depth", "Detection of errors"], c: "Prevention of frauds" },
            { q: "118. Cut-off testing is performed during audit of sales to address the following assertion", o: ["Occurrence", "Measurement", "Cut-off", "All of these"], c: "Cut-off" },
            { q: "119. Which of the following is/are advantage/s of audit?", o: ["Audit is a tool, which different stakeholders can use to protect their interests in the enterprise", "Audit is not only a corrective measure but has a deterrent effect. It serves as a moral check on the employees from committing defalcations or embezzlements", "The employees of the organisation remain alert and vigilant as regards the updating of books of accounts and other records", "All of these"], c: "The employees of the organisation remain alert and vigilant as regards the updating of books of accounts and other records" },
            { q: "120. ____ involves examination of legalities by blending the techniques of propriety audit, regularity, investigative and financial audits.", o: ["Forensic audit", "Tax audit", "Cost audit", "Human Resource Audit"], c: "Forensic audit" }
        ]
    },
    {
        setName: "Set 9",
        questions: [
            { q: "121. Audit Documentation is related to", o: ["SA 300", "SA 230", "SA 250", "SA 310"], c: "SA 230" },
            { q: "122. ____ is a detailed plan of the auditing work to be performed, specifying the procedures to be followed in verification of each item and the financial statements and the estimated time required.", o: ["Audit programme", "Flow-chart", "Audit Documentation", "Audit Working Papers"], c: "Audit programme" },
            { q: "123. ____ refers to the possibility of material misstatement due to complex transactions or even due to organised fraud.", o: ["Control Risk", "Inherent Risk", "Detection Risk", "None of these"], c: "Inherent Risk" },
            { q: "124. Benefits of Audit Sampling are", o: ["It reduces the workload of the auditor", "It saves time and cost", "It gives dependable result as it is based on statistical sampling methods", "All of these"], c: "All of these" },
            { q: "125. The main role of ____ is the following: A. Recommending Auditing Standards, B. Monitoring and Enforcing Compliance with Auditing Standards and C. Power to Investigate", o: ["NFRA", "NACAS", "IFC", "None of these"], c: "NFRA" },
            { q: "126. NFRA consists which of the following?", o: ["Accounting Standards Committee", "Auditing Standards Committee", "Enforcement Committee", "All of these"], c: "All of these" },
            { q: "127. the term ____ means the policies and procedures adopted by the company for ensuring the orderly and efficient conduct of its business, including adherence to company's policies, the safeguarding of its assets, the prevention and detection of frauds and errors, the accuracy and completeness of the accounting records, and the timely preparation of reliable financial information.", o: ["Enforcement Committee", "Internal Financial Controls", "National Advisory Committee on Accounting Standards", "National Financial Reporting Authority"], c: "Internal Financial Controls" },
            { q: "128. Which of the following is not a duty of duties of the NFRA?", o: ["Recommend accounting and auditing policies and standards to be adopted by companies for approval by the Central Government.", "Monitor and enforce compliance with Income Tax Act and auditing standards.", "Perform such other functions and duties as may be necessary or incidental to the aforesaid functions and duties.", "Oversee the quality of service of the professions associated with ensuring compliance with such standards and suggest measures for improvement in the quality of service."], c: "Monitor and enforce compliance with Income Tax Act and auditing standards." },
            { q: "129. An auditor expresses ____ opinion on financial statements when the auditor, having obtained sufficient appropriate audit evidence, concludes that misstatements, either individually or in aggregate, are both material and pervasive to the financial statements.", o: ["Qualified", "Disclaimer", "Adverse", "None of these"], c: "Adverse" },
            { q: "130. Some situations when an auditor should express a qualified opinion is/are", o: ["Non-adherence to AS-2 with regard to inventory valuation at the lower of cost and net realisable value.", "Auditor being prevented by the management from observing the counting of physical inventory where such action is material to the financial statements.", "Both 1 and 2", "Non-receipt of branch audit reports from a significant number of branches."], c: "Both 1 and 2" },
            { q: "131. An audit report with an unmodified opinion is also known as ____ or 'Unqualified Report'", o: ["Clean Report", "Clear Report", "Neet Report", "Honest Report"], c: "Clean Report" },
            { q: "132. Basic Elements of Audit Report as per Standards on Auditing are", o: ["Key Audit Matters", "Auditor's Opinion", "Basis for Opinion", "All of these"], c: "All of these" },
            { q: "133. As per Rule 11 of Companies (Audit and Auditors) Rules 2014, the auditor's report shall also include his views and comments on which of the following matters?", o: ["whether the company has disclosed the impact, if any, of pending litigations on its financial position in its financial statement:", "whether the company has made provision, as required under any law or accounting standards, for material foreseeable losses, if any, on long term contracts including derivative contracts", "whether there has been any delay in transferring amounts, required to be transferred, to the Investor Education and Protection Fund by the company.", "All of these"], c: "All of these" },
            { q: "134. Essential Characteristics of a Good Audit Report are", o: ["Simplicity, Clarity, Brevity, Firmness, Objectivity, Disclosure, Impartiality, Information-based and Timeliness", "Simplicity, Clarity, Brevity, Firmness, Objectivity, Disclosure, Impartiality, Information-based and Popularity", "Simplicity, Clarity, Brevity, Firmness, Objectivity, Disclosure, Impartiality, Information-based and ambiguity", "None of these"], c: "Simplicity, Clarity, Brevity, Firmness, Objectivity, Disclosure, Impartiality, Information-based and Timeliness" },
            { q: "135. Auditor shall verify whether the unpaid dividend has been transferred to the Unpaid Dividend Account within ____ days from the expiry of ____ days allowed for declaration and payment of dividend.", o: ["7, 20", "7, 30", "15, 20", "15, 15"], c: "7, 30" }
        ]
    },
    {
        setName: "Set 10",
        questions: [
            { q: "136. If debentures are redeemable, it can be redeemed in which of the following ways?", o: ["By way of payment as donation", "By payment whenever the company desires to do so", "By way of personal drawing", "By way of payment as shares without consideration"], c: "By payment whenever the company desires to do so" },
            { q: "137. The audit procedure to be applied in this context of Splitting of Shares are", o: ["The auditor shall confirm that alteration was authorised by articles", "He should verify the minutes of the Board meeting and ordinary resolution passed in the general meeting in which the approval of members is obtained", "He should verify that alteration had been effected in copies of Memorandum, Articles, etc.", "All of these"], c: "All of these" },
            { q: "138. The term ____ comprises both trade creditors (i.e., sundry creditors) as well as bills payable. This represents the liability of an organisation to its suppliers.", o: ["Trade Payable", "Rights and Obligations"], c: "Trade Payable" },
            { q: "139. Audit Report contains", o: ["Details of Facts", "Details of Frauds", "Expression of Opinion", "Expression of Suggestions"], c: "Expression of Opinion" },
            { q: "140. Audit Certificate contains", o: ["Details of Facts", "Details of Frauds", "Expression of Opinion", "Expression of Suggestions"], c: "Details of Facts" },
            { q: "141. An auditor expresses ____ opinion on financial statements when the auditor, having obtained sufficient appropriate audit evidence, concludes that misstatements, either individually or in aggregate, are both material and pervasive to the financial statements.", o: ["Qualified", "Adverse", "Modified", "Disclaimer of"], c: "Adverse" },
            { q: "142. Any casual vacancy in a govt. company is filled by the CAG of India within ____ days.", o: ["15", "30", "45", "60"], c: "30" },
            { q: "143. A cost auditor submits his report along with reservations and observations in Form No.", o: ["CRA 1", "CRA 2", "CRA 3", "CRA 4"], c: "CRA 3" },
            { q: "144. Secretarial Audit is covered under section", o: ["204", "148", "139", "133"], c: "204" },
            { q: "145. An auditor shall submit a unmodified report when", o: ["The financial statements exhibit true and fair view", "The financial statements are partially correct", "The financial statements are incomplete", "The financial statements are unavailable"], c: "The financial statements exhibit true and fair view" },
            { q: "146. Which of the following is not a content of audit report as per CARO?", o: ["Inventory", "Acceptance of deposit", "Recruitment of employees", "Repayment of loan"], c: "Recruitment of employees" },
            { q: "147. Which of the following are the essential characteristics of a good audit report?", o: ["Simplicity", "Clarity", "Objectivity", "All of these"], c: "All of these" },
            { q: "148. Auditor of a company appointed u/s ____ shall not act as the cost auditor of the company.", o: ["139", "148", "204", "141"], c: "139" },
            { q: "149. As per Section 139(9), a retiring auditor may be re-appointed at an annual general meeting, if:", o: ["he is not disqualified for re-appointment", "he has not given the company a notice in writing of his unwillingness to be re-appointed", "a special resolution has not been passed at that meeting appointing some other auditor or providing expressly that he shall not be re-appointed", "All of these"], c: "All of these" },
            { q: "150. The first auditor of a company, other than a Government company, shall be appointed by the ____ within thirty days from the date of registration of the company.", o: ["Shareholders", "Board of Directors", "Government", "Employees"], c: "Board of Directors" }
        ]
    },
    {
        setName: "Set 11",
        questions: [
            { q: "151. The company shall inform the auditor concerned of his or its appointment, and also file a notice of such appointment with the Registrar within fifteen days of the meeting in which the auditor is appointed in Form No.", o: ["ADT 1", "ADT 2", "ADT 3", "ADT 4"], c: "ADT 1" },
            { q: "152. No individual shall be appointed or reappointed as auditor for more than one term of ____ consecutive years", o: ["4", "5", "6", "3"], c: "5" },
            { q: "153. Section ____ of Companies Act, 2013 contains the statutory provisions in relation to remuneration of auditors", o: ["139", "148", "142", "141"], c: "142" },
            { q: "154. ____ refers to the process of conducting the audit of a single organisation by more than one auditor.", o: ["Joint audit", "Cost audit", "Internal audit", "Continuous audit"], c: "Joint audit" },
            { q: "155. The amendments that gave the local self-governance in India the constitutional protection are ____ and ____", o: ["53 and 54", "63 and 64", "73 and 74", "83 and 84"], c: "73 and 74" },
            { q: "156. According to the Central Co-operatives Societies Act, ____ of the profits of a co-operative society should be transferred to a Reserve Fund before distribution of dividend or payment of bonus to its members.", o: ["20%", "25%", "30%", "35%"], c: "25%" },
            { q: "157. The major objective of audit of Municipalities and Panchayats are", o: ["To ensure on the fairness and correctness of contents in the Financial Statement", "To report on adequacy of Internal control", "To ensure value of money is fully received on amount spent.", "All of these"], c: "All of these" },
            { q: "158. Which of the following records are not maintained by a co-operative societies as accounting records?", o: ["Cash book", "Memorandum of Association", "Register of assets and investments", "Register of sureties"], c: "Memorandum of Association" },
            { q: "159. According to the Central Co-operatives Societies Act, ____ % of the profits of a co-operative society should be transferred to a Reserve Fund before distribution of dividend or payment of bonus to its members.", o: ["25", "20", "30", "15"], c: "25" },
            { q: "160. Which of the following is not falling under the broad category of Banks?", o: ["Commercial Banks", "Regional Rural Banks", "Co-operative Banks", "None of these"], c: "None of these" },
            { q: "161. The auditor of a nationalised bank is primarily required to comment on which the following aspects in its report to the Central Government?", o: ["whether the financial statements present a true and fair view of the affairs of the bank and whether all necessary explanation and information has been made available to him", "whether or not the monetary supports received from the offices and branches of the bank have been found adequate for the purpose of his audit", "whether or not the transactions of the bank, which have come to his notice, have been within the powers of that bank", "Both 1 and 3"], c: "Both 1 and 3" },
            { q: "162. In relation to advances made by bank an auditor needs to review which of the followings?", o: ["Scrutinise the subsidiary, ledger, & control accounts", "Scrutinise the overdue account and scheme for recovery of such amount.", "Ensure the proper documentation of account.", "All of these"], c: "All of these" },
            { q: "163. Hospitality sector covers a wide range of organisations which can broadly be divided into ____ categories", o: ["4", "3", "2", "1"], c: "4" },
            { q: "164. Steps common for the category of Restaurants in relation to Hospitality Sector is/are", o: ["Vouch revenue out of commissions from various companies and tour partners.", "Verify the total revenue recognised based on the daily and monthly sales report.", "Check that the revenue has been realised in cash based on bank statements. Check whether arrears written off, if any. has been duly approved by the person responsible.", "Both 2 and 3"], c: "Both 2 and 3" },
            { q: "165. Regarding which category of Hospitality Sector, the following steps are taken for auditing purposes? a) Vouch the collections from boarders based on their check-in and check-out information recorded in the register, counterfoils of bills and cash book. b) Verify the room rent receipts and daily occupancy reports. Ask for proper clarification for differential rent charged from any boarder. Be careful while verifying the adjustment of unrealised room rent, cancellation charges of booking accommodation at the time of closing of accounts. c) Vouch collections on account of special events such as conferences, wedding ceremony etc. separately based on counterfoil of receipts and cash book.", o: ["Amusement Park", "Cinema Halls", "Hotels and Guest Houses", "Travel and Tourism"], c: "Hotels and Guest Houses" }
        ]
    },
    {
        setName: "Set 12",
        questions: [
            { q: "166. Steps of audit common for all organisations are", o: ["Understand the ownership structure of the organisation", "Evaluate the internal control system and determine the nature, timing and the extent of the audit procedures", "Check that the organisation has a valid licence from an appropriate authority to run the business", "All of these"], c: "All of these" },
            { q: "167. Forfeiture of shares means:", o: ["Issuance of new shares", "Buying back of shares", "Cancellation of shares due to non-payment of call money", "Transfer of shares"], c: "Cancellation of shares due to non-payment of call money" },
            { q: "168. After forfeiture, the forfeited shares can be:", o: ["Re-issued", "Destroyed", "Converted into debentures", "Held in treasury"], c: "Re-issued" },
            { q: "169. Rights shares are generally offered in proportion to:", o: ["Debentures held", "Number of years associated with the company", "Shares already held", "Voting rights"], c: "Shares already held" },
            { q: "170. Buy-back of shares reduces:", o: ["Authorized share capital", "Issued share capital", "Subscribed share capital", "Paid-up share capital"], c: "Paid-up share capital" },
            { q: "171. A company announces bonus shares in the ratio 2:5. A shareholder holds 1,000 shares. How many bonus shares will he receive?", o: ["200", "400", "250", "500"], c: "400" },
            { q: "172. A company buys back 5,000 shares of ₹10 each at ₹12. What is the total amount paid for buy-back?", o: ["Rs.50,000", "Rs.60,000", "Rs.55,000", "Rs.65,000"], c: "Rs.60,000" },
            { q: "173. A company issued 8,000 shares and received applications for 10,000 shares. Pro-rata allotment is made. A person applied for 500 shares. How many shares will he get?", o: ["500", "400", "300", "350"], c: "400" },
            { q: "174. A company issued 5,000 shares of ₹10 each at a premium of ₹2 per share. What is the total amount of securities premium received?", o: ["Rs.60,000", "Rs.5,000", "Rs.10,000", "Rs.20,000"], c: "Rs.10,000" },
            { q: "175. Employee is granted 1,000 stock options at ₹60. Market price at time of exercise is ₹100. What is the total gain to the employee?", o: ["Rs.60,000", "Rs.40,000", "Rs.1,00,000", "Rs.20,000"], c: "Rs.40,000" },
            { q: "176. Preference shares of ₹1,00,000 are redeemed at a premium of 5%. What amount should be debited to Securities Premium Account (if available)?", o: ["Rs.1,00,000", "Rs.1", "Rs.5,000", "None of these"], c: "Rs.5,000" },
            { q: "177. According to Schedule III of the Companies Act, 2013, which of the following is classified under 'Current Assets'?", o: ["Inventories", "Fixed Assets", "Long-term Investments", "Intangible Assets"], c: "Inventories" },
            { q: "178. Which section of Schedule III deals with the format and disclosure requirements for the Statement of Profit and Loss?", o: ["Part I", "Part II", "Part III", "Part IV"], c: "Part II" },
            { q: "179. Which of the following expenses is shown separately in the Statement of Profit and Loss as per Schedule III?", o: ["Depreciation and amortization expense", "Cost of goods sold", "Dividend paid", "Loans and advances"], c: "Depreciation and amortization expense" },
            { q: "180. According to Schedule III, under which head is 'Capital Reserve' shown?", o: ["Current liabilities", "Non-current liabilities", "Equity", "Non-current assets"], c: "Equity" }
        ]
    },
    {
        setName: "Set 13",
        questions: [
            { q: "181. A company has the following information: Inventory: ₹1,50,000, Trade Receivables: ₹2,00,000, Cash and Cash Equivalents: ₹50,000, Prepaid Expenses: ₹10,000, Short-term loans and advances: ₹40,000. What is the total amount classified as Current Assets in the Balance Sheet?", o: ["Rs.4,00,000", "Rs.3,50,000", "Rs.4,50,000", "Rs.4,00,000"], c: "Rs.4,50,000" },
            { q: "182. The company's Balance Sheet shows the following liabilities: Long-term borrowings: ₹5,00,000, Trade payables: ₹1,00,000, Current maturities of long-term debt: ₹80,000, Provision for taxation: ₹50,000. What is the total Current Liabilities amount?", o: ["Rs.2,50,000", "Rs.1,70,000", "Rs.2,30,000", "Rs.1,50,000"], c: "Rs.2,30,000" },
            { q: "183. Cash flows from which of the following activities include receipts from sale of goods and services?", o: ["Operating Activities", "Investing Activities", "Financing Activities", "None of these"], c: "Operating Activities" },
            { q: "184. Which of the following is NOT included in cash flows from investing activities?", o: ["Purchase of fixed assets", "Proceeds from sale of fixed assets", "Payment of interest on loans", "Purchase of investments"], c: "Payment of interest on loans" },
            { q: "185. A company has the following information: Net Profit after tax: Rs. 7,00,000. Depreciation charged: Rs. 1,20,000. Increase in Trade Receivables: Rs. 40,000. Decrease in Trade Payables: Rs. 30,000. What is the net cash from operating activities (Indirect Method)?", o: ["Rs.5,10,000", "Rs.8,90,000", "Rs.8,20,000", "Rs.7,50,000"], c: "Rs.7,50,000" },
            { q: "186. If the net cash from operating activities is Rs. 9,00,000, net cash used in investing activities is Rs. (4,00,000), and net cash used in financing activities is Rs. (3,00,000), what is the net increase in cash and cash equivalents during the year?", o: ["Rs.5,00,000", "Rs.(2,00,000)", "Rs.2,00,000", "Rs.(5,00,000)"], c: "Rs.2,00,000" },
            { q: "187. Permanent Audit file contains", o: ["Audit Programme", "Analysis of significant ratios and trends", "Copies of management letters", "Analysis of transaction and balances"], c: "Analysis of significant ratios and trends" },
            { q: "188. Objective of an Audit is to formulate an overall opinion on", o: ["Financial Statement", "Books of Accounts", "Cost Statement", "None of these"], c: "Financial Statement" },
            { q: "189. SA-700 stands for", o: ["Joint Auditor", "Audit Planning", "Forming an opinion and reporting on Financial Statement", "None of the above"], c: "Forming an opinion and reporting on Financial Statement" },
            { q: "190. Audit is a fact-finding process that compares actual results with", o: ["Premature results", "Specified standards and plans", "Expected results", "Preliminary results"], c: "Specified standards and plans" },
            { q: "191. An audit report is the ____ product of audit", o: ["Final", "Main", "Semi final", "None of the above"], c: "Final" },
            { q: "192. Audit Procedures to obtain audit evidences include", o: ["Substantive Procedure", "Compliance Procedure", "Both (A) and (B)", "Neither (A) nor (B)"], c: "Both (A) and (B)" },
            { q: "193. An auditor should submit a Disclaimer of Opinion when", o: ["he has certain reservations as to the presentation of truth and fairness in financial statements", "he is satisfied with the truth and fairness of financial statements", "some material information is not available", "the effect of any disagreement with the management is not so material"], c: "some material information is not available" },
            { q: "194. SA 230 stands for", o: ["Agreeing the terms of Audit engagements", "Quality control for an audit of financial Statements", "Responsibility of Joint Auditor", "Audit Documentation"], c: "Audit Documentation" },
            { q: "195. Audit is conducted to draw overall opinion on", o: ["Income Statement", "Financial Statement", "Cost Statement", "None of the above"], c: "Financial Statement" }
        ]
    },
    {
        setName: "Set 14",
        questions: [
            { q: "196. The purpose of internal audit is to protect the", o: ["Assets", "Audit staff", "Management", "Accountant"], c: "Assets" },
            { q: "197. Form for Secretarial Audit Report is-", o: ["MR-1", "MR-2", "MR-3", "MR-4"], c: "MR-3" },
            { q: "198. The purpose of Internal audit is to detect the error in the", o: ["Employees records", "Accounting records", "Cash records", "Bank records"], c: "Accounting records" },
            { q: "199. Chartered Accountants have to retain the working papers for", o: ["2 yrs", "3 yrs", "5 yrs", "7 yrs"], c: "7 yrs" },
            { q: "200. The meetings of Audit committee should be in a year", o: ["2", "3", "4", "5"], c: "4" },
            { q: "201. SA 210 stands for-", o: ["Agreeing the terms of Audit engagements.", "Quality control for an audit of financial Statements", "Responsibility of Joint Auditor", "Audit Documentation"], c: "Agreeing the terms of Audit engagements." },
            { q: "202. The ____ shall act as the secretary of the Audit Committee.", o: ["Auditor", "Employee", "Company Secretary", "Chairman"], c: "Company Secretary" },
            { q: "203. Check list contains the instruction to be followed by the -", o: ["Audit Assistants", "Internal Auditor", "Employee of the organization", "External Auditor"], c: "Audit Assistants" },
            { q: "204. The function of internal audit is meant for-", o: ["Dearth of time", "Dearth of Staff", "Dearth of time and funds", "Dearth of funds"], c: "Dearth of time" },
            { q: "205. An auditor is required to retain the books of accounts for how long?", o: ["3 yrs", "1 yrs", "7 yrs", "None of the above"], c: "7 yrs" },
            { q: "206. Permanent Audit File does not contain", o: ["significant audit observations of earlier years", "Permanent Audit File does not contain", "analysis of significant ratios and trends", "copies of management letters"], c: "copies of management letters" },
            { q: "207. A Cost Auditor submits his report to", o: ["Government", "Shareholders", "Board of Directors", "Statutory Auditor"], c: "Board of Directors" },
            { q: "208. In case of a company other than a Government Company, any casual vacancy in the post of auditor is to be filled by the", o: ["Comptroller and Auditor General (CAG)", "Board of Directors", "Managing Director", "Shareholders"], c: "Board of Directors" },
            { q: "209. While conducting audit of financial statement auditor need to comply with", o: ["Cost Audit Standards", "Auditing Standards", "Secretarial standards", "None of the above"], c: "Auditing Standards" },
            { q: "210. Statutory Auditor can be removed by the", o: ["BOD", "Audit committee", "Shareholders", "None of the above"], c: "Shareholders" }
        ]
    },
    {
        setName: "Set 15",
        questions: [
            { q: "211. Review of internal control system is very important for the auditor as the effectives of internal control system will determine the extent of checking to be done by the:", o: ["Auditor", "Accountant", "Management", "None of the above"], c: "Auditor" },
            { q: "212. As per SQC 1, Audit working papers should be retained for a period of", o: ["2 years", "5 years", "7 years", "10 years"], c: "7 years" },
            { q: "213. Unpaid dividend standing at the credit of Unpaid Dividend A/C should be transferred to Investor Education and Protection Fund after ____ years of its remaining unpaid.", o: ["eight", "six", "seven", "five"], c: "seven" },
            { q: "214. Current Audit file contains-", o: ["Analysis of significant ratios and trends", "AOA and MOA of the company", "Audit programme", "Notes regarding significant accounting policies"], c: "Audit programme" },
            { q: "215. Form for maintenance of Cost Records by the Company is", o: ["CRA-1", "CRA-2", "CRA-3", "CRA-4"], c: "CRA-1" },
            { q: "216. Various types of quality audits are:", o: ["Management (system)", "Registration (certification)", "Product", "All of above"], c: "All of above" },
            { q: "217. Statutory Auditor is appointed by the shareholder in the", o: ["Statutory Meeting", "Board Meeting", "General Meeting", "EGM"], c: "General Meeting" },
            { q: "218. The ____ is also expected to provide the resources needed and select staff members to accompany the auditors.", o: ["Client", "Auditor", "Internal auditor", "Auditee"], c: "Auditee" },
            { q: "219. Final Audit is known as", o: ["Internal Audit", "Tax Audit", "Annual Audit", "All of the above"], c: "Annual Audit" },
            { q: "220. Proving the truth means vouching of", o: ["Expenses", "Payment", "Liabilities", "Assets"], c: "Expenses" },
            { q: "221. The most comprehensive type of audit is the ____ system audit, which examines suitability and effectiveness of the system as a whole.", o: ["Quality", "Quantity", "Preliminary", "Sequential"], c: "Quantity" },
            { q: "222. The purpose of internal audit is to determine liabilities of", o: ["Employees", "Employer", "Accountant", "External auditor"], c: "Employees" },
            { q: "223. CAAT stands for-", o: ["Cornwall Air Ambulance Trust", "Center for alternatives to Animal Testing", "Children Air Ambulance Trust", "Computer Assisted Auditing Technique"], c: "Computer Assisted Auditing Technique" },
            { q: "224. Maximum term of Individual Auditor", o: ["1 term of 5 years", "2 term of 5 years", "3 term of 5 years", "None of the above"], c: "1 term of 5 years" },
            { q: "225. If the Debentures are issued as collateral security either to Banks or Creditors the Auditor needs to ensure that such issue is approved by", o: ["Debenture Trustee", "Shareholders", "Audit Committee", "Board of Directors"], c: "Board of Directors" }
        ]
    },
    {
        setName: "Set 16",
        questions: [
            { q: "226. The first Auditor of a Company shall be appointed by the Board of Directors within", o: ["30 days from the date of first AGM", "30 days from the date of registration", "90 days from the date of registration", "1 year from the date of registration"], c: "30 days from the date of registration" },
            { q: "227. Cost Audit can be done by the-", o: ["Secretarial Auditor", "Employee of the organization", "Cost Auditor", "None of the above"], c: "Cost Auditor" },
            { q: "228. When the auditor is an employee of the organization being audited (auditee), the audit is classified as a Quality audit", o: ["External", "Internal", "Compliance", "Both A & B"], c: "Internal" },
            { q: "229. Secretarial Audit can be done by-", o: ["Cost Auditor", "Employee of the organization", "Secretarial Auditor", "None of the above"], c: "Secretarial Auditor" },
            { q: "230. Secretarial Audit is applicable to the public sector company having the turnover of-", o: ["50 crore", "200 crore", "250 crore", "500 crore"], c: "250 crore" },
            { q: "231. An Audit Committee should have a minimum of ____ number of directors.", o: ["3", "4", "5", "6"], c: "3" },
            { q: "232. SA 530 stands for", o: ["Audit Sampling", "Audit Documentation", "Agreeing the terms of Audit Engagements", "Responsibility of Joint Auditor"], c: "Audit Sampling" },
            { q: "233. A nomination and remuneration committee should have ____ directors.", o: ["2", "4", "3", "6"], c: "3" },
            { q: "234. Which of the following is not an audit risk?", o: ["Control Risk", "Omission Risk", "Detection Risk", "Inherent Risk"], c: "Omission Risk" },
            { q: "235. Which of the following services cannot be rendered by an auditor as per Companies Act 2013?", o: ["Verification of assets and liabilities", "Vouching", "Providing investment advisory services", "Issuing certificates on relevant matters"], c: "Providing investment advisory services" },
            { q: "236. SA 300 stands for", o: ["Audit Planning", "Responsibility of Joint Auditor", "Overall planning of audit", "None of the above"], c: "Audit Planning" },
            { q: "237. Ind AS 16 deals with:", o: ["Leases", "Revenue from Contracts with Customers", "Property, Plant, and Equipment", "Financial Instruments"], c: "Property, Plant, and Equipment" },
            { q: "238. Ind AS 38 deals with:", o: ["Revenue recognition", "Intangible assets", "Tangible assets", "Borrowing costs"], c: "Intangible assets" },
            { q: "239. Ind AS 33 relates to:", o: ["Earnings Per Share", "Segment Reporting", "Income Taxes", "Inventories"], c: "Earnings Per Share" },
            { q: "240. Ind AS 21 deals with:", o: ["The Effects of Changes in Foreign Exchange Rates", "Segment Reporting", "Income Taxes", "Earnings Per Share"], c: "The Effects of Changes in Foreign Exchange Rates" }
        ]
    }
];