// --- DATA: Chronologically Ordered Sets (Converted from MA set.html) ---
const quizSets = [
    {
        setName: "Set 1",
        questions: [
            { q: "1. Management Accounting", o: ["Accumulates, summarizes and analyses the available data.", "Is primarily concerned with the requirements of the management.", "Makes Corporate Planning and Strategy effective.", "All of the above"], c: "All of the above" },
            { q: "2. Management accounting can be viewed as", o: ["Marketing-oriented Accounting", "Management-oriented Accounting", "Accounting-oriented Management", "Manager-oriented Accounting"], c: "Management-oriented Accounting" },
            { q: "3. The main objective of management accounting is", o: ["To maintain the accounting records", "To know the amount due from customers and suppliers", "To ascertain analyse and interpret the results of business operations", "To record all the business transactions"], c: "To ascertain analyse and interpret the results of business operations" },
            { q: "4. \_\_\_\_ is the study of managerial aspects of financial accounting", o: ["Cost accounting", "Financial accounting", "Management accounting", "Business accounting"], c: "Management accounting" },
            { q: "5. The purpose of management accounting is to help make decisions", o: ["Managers", "Investors", "Marketers", "Banks"], c: "Managers" },
            { q: "6. Management accounting assists the management in", o: ["Planning", "Directing", "Controlling", "All of the above"], c: "All of the above" },
            { q: "7. Period of lost relevance is the \_\_\_\_ of the evolution of management accounting.", o: ["Ist stage", "2nd stage", "3rd stage", "4th stage"], c: "3rd stage" },
            { q: "8. \_\_\_\_ criteria are a set of standards for a company's behaviour used by socially conscious investors to screen potential investments.", o: ["JIT", "AMT", "ESG", "ABC"], c: "ESG" },
            { q: "9. Management accounting information helps managers formulate strategy by answering which of the following questions?", o: ["Who are the most important customers, and how can the company deliver value to the customers?", "What is most critical capability of the company which may be technology, production, or marketing?", "How can we leverage it for new strategic initiatives?", "All of the above"], c: "All of the above" },
            { q: "10. Management accounting with specific focus on environmental issues is becoming increasingly important in organizations as environmental costs are large in many organisations. There are three specific reasons for this, which are", o: ["Environmental costs are often high in the many manufacturing organisations", "Regulatory requirements often impose huge fines for non-compliance", "Both 1 and 2", "Companies are increasingly realizing that being socially and environmentally responsible declines their image and this has positive impact on their bottom line."], c: "Both 1 and 2" },
            { q: "11. Management accounting is concerned with data collection from", o: ["internal sources", "external sources", "internal and external sources", "Internal or external sources"], c: "internal and external sources" },
            { q: "12. Management Accounting is concerned with accounting information, which is useful to the management This definition is given by", o: ["Robert N. Antho", "Brown and Howard", "CIMA", "The Institute of Chartered Accountants of England and Wales"], c: "Robert N. Antho" },
            { q: "13. The primary objective of Management Accounting is to", o: ["maximize profits", "minimize losses", "maximize profits or minimize losses", "All of the above"], c: "All of the above" },
            { q: "14. Which of the following is a correct definition of activity-based management?", o: ["An approach to the costing and monitoring of activities which involves tracing resource consumption and costing final outputs. Resources are assigned to activities and activities to cost objects based on consumption estimates. The latter utilize cost drivers to attach activity costs to outputs.", "The identification and evaluation of the activity drivers used to trace the cost of activities to cost objects. It may also involve selecting activity drivers with potential to contribute to the cost management function with particular reference to cost reduction", "A method of budgeting based on an activity framework and utilizing cost driver data in the budget-setting and variance feedback processes.", "A system of management which uses activity-based cost information for a variety of purposes including cost reduction, cost modeling and customer profitability analysis"], c: "A system of management which uses activity-based cost information for a variety of purposes including cost reduction, cost modeling and customer profitability analysis" },
            { q: "15. Which of the following characteristics would be an indicator that a company would benefit from switching to activity based costing?", o: ["Only one homogenous product is produced on a continuous basis", "The existing cost system is reliable and has produced excellent results", "Overhead costs are high and increasing and no one seems to know why", "The costs of implementing ABC out-weigh the benefits"], c: "Overhead costs are high and increasing and no one seems to know why" }
        ]
    },
    {
        setName: "Set 2",
        questions: [
            { q: "16. According to the Chartered Institute of Management Accountants (CIMA), cost attribution to cost units on the basis of benefits received from indirect activities e.g. ordering, setting up, and assuring quality is known as:", o: ["Absorption costing", "Marginal costing", "Activity-based-costing", "Job costing"], c: "Activity-based-costing" },
            { q: "17. In an ABC system, which of the following is likely to be classified as a batch level activity?", o: ["Machine set-up", "Product design", "Inspection of every item produced", "Production manager's work"], c: "Machine set-up" },
            { q: "18. Activity based costing", o: ["Uses a plant wide overhead rate to assign overhead", "Is not expensive to implement", "Typically applies overhead costs using direct labour hours", "Uses multiple activity rates"], c: "Uses multiple activity rates" },
            { q: "19. Which of the following activities is not a batch level activity?", o: ["Processing purchase orders", "Designing products", "Receive raw materials from suppliers", "Setting up equipment"], c: "Designing products" },
            { q: "20. Which of the following is not included in batch level activities?", o: ["Material ordering cost", "Machine set-up cost", "Inspection cost", "Designing the product"], c: "Designing the product" },
            { q: "21. Assigning overhead using ABC often:", o: ["Shifts overhead costs from high-volume products to low-volume products", "Shifts overhead costs from low-volume products to high-volume products", "Provides the same results as traditional costing", "Requires one predetermined overhead rate"], c: "Shifts overhead costs from high-volume products to low-volume products" },
            { q: "22. In Activity Based Costing", o: ["Non-manufacturing costs may not be assigned to products", "Some manufacturing costs may be excluded from product costs", "Allocation bases are the same as those used in traditional costing methods", "Similar to traditional costing. ABC only uses one overhead cost pool"], c: "Some manufacturing costs may be excluded from product costs" },
            { q: "23. In an ABC system, the allocation bases that are used for applying costs to services or procedures are called:", o: ["Cost Pool", "Cost Driver", "Cost Absorption", "Cost Object"], c: "Cost Driver" },
            { q: "24. Which of the following would not be deducted from sales in a management report prepared using ABC?", o: ["Direct materials", "Direct labour", "Variable selling and administration costs", "Shipping costs"], c: "Shipping costs" },
            { q: "25. \_\_\_\_ an item for which cost measurement is required e.g. product, job or a customer", o: ["Cost Pool", "Cost Driver", "Cost Absorption", "Cost Object"], c: "Cost Object" },
            { q: "26. Which of the following is different in ABC when compared to traditional costing?", o: ["Traditional costing and ABC costing usually yield very similar product costs", "In an ABC costing system, costs are only assigned to products that actually required work that gave rise to a particular cost", "In ABC, batch-level costs are applied to products using unit-level bases", "Under traditional costing, batch-level costs are shifted from high-volume products to low-volume products"], c: "In an ABC costing system, costs are only assigned to products that actually required work that gave rise to a particular cost" },
            { q: "27. Process of Cost allocation under Activity Based Costing is", o: ["Cost of Activities \u2192 Activities \u2192 Cost Driver \u2192 Cost allocated to cost objects", "Cost Driver \u2192 Cost of Activities \u2192 Cost allocated to cost objects \u2192 Activities", "Activities \u2192 Cost of Activities \u2192 Cost Driver \u2192 Cost allocated to cost objects", "Activities \u2192 Cost Driver \u2192 Cost allocated to cost objects \u2192 Cost of Activities"], c: "Activities \u2192 Cost of Activities \u2192 Cost Driver \u2192 Cost allocated to cost objects" },
            { q: "28. Cost of maintaining a building is:", o: ["Unit Level Cost", "Batch Level Cost", "Product Level Cost", "Facility Level Cost"], c: "Facility Level Cost" },
            { q: "29. \_\_\_\_ should be subtracted from net product revenues instead of an arbitrary and illogical apportionment.", o: ["Facility Level Cost", "Product Level Cost", "Organizational Level Cost", "High Level Cost"], c: "Organizational Level Cost" },
            { q: "30. The basis of apportionment of overheads which takes into account the profitability of various departments is called:", o: ["FIFO basis", "LIFO basis", "Ability to pay basis", "Activity basis"], c: "Activity basis" }
        ]
    },
    {
        setName: "Set 3",
        questions: [
            { q: "31. Which of the following is the main cost driver of customer order processing activity?", o: ["Flow of the product from the assembly line", "Order value", "Number of problem suppliers", "Number of machine charges"], c: "Order value" },
            { q: "32. Painting the product would be an example of which activity level groups", o: ["Facility-level activity", "Product-level activity", "Unit-level activity", "Batch-level activity"], c: "Unit-level activity" },
            { q: "33. Which of the following tasks is not normally associated with an activity-based costing system?", o: ["Calculation of cost application rates", "Identification of cost pools", "Preparation of allocation matrices", "Identification of cost drivers"], c: "Preparation of allocation matrices" },
            { q: "34. All of the following are examples of batch level activities except:", o: ["Purchase order processing", "Setting up equipment", "The clerical activity associated with processing purchase orders to pro-duce an order for a standard product", "Worker recreational facilities"], c: "Worker recreational facilities" },
            { q: "35. A cost driver-", o: ["is a force behind the overhaed cost", "is an allocation base", "is a transaction that is a significant determinant of cost", "is all of the above"], c: "is all of the above" },
            { q: "36. Which of these is NOT a cost driver For the Activity Design of products, services & Processes?", o: ["Number of Products in design", "Number of Parts per product", "Number of employee Training Programmes", "Number of engineering Hours"], c: "Number of employee Training Programmes" },
            { q: "37. Which of these in NOT a Cost driver for Marketing and sales Function?", o: ["Number of advertisements/Insertions", "Number of researche projects", "Number of Sales personnel", "sales Revenue"], c: "Number of researche projects" },
            { q: "38. Which of these in NOT a Cost driver for Customer Service Activity?", o: ["Number of service calls", "Number of Products serviced", "Hours spent on servicing products", "sales Revenue"], c: "sales Revenue" },
            { q: "39. Plant depreciation is an example of which activity-level group?", o: ["Unit-level activity", "Batch-level activity", "Product-level activity", "Facility-level activity"], c: "Facility-level activity" },
            { q: "40. Under activity-based costing, 'material ordering' is considered as \_\_\_\_", o: ["Unit-level activity", "Facility-level activity", "Batch-level activity", "Product-level activity"], c: "Batch-level activity" },
            { q: "41. Samsung an appliance manufacturer is developing a new line of ovens that uses controlled-laser technology. Research and testing costs associated with the new ovens is said to arise from a:", o: ["Unit Level Activity", "Competitive Level Activity", "Facility Level Activity", "Product Sustaining Activity"], c: "Product Sustaining Activity" },
            { q: "42. A homogeneous cost pool is one that:", o: ["Does not change over time", "Needs many activity drivers to be allocated to a cost object", "Can be explained with a single activity driver", "Has only one type of material assigned to it"], c: "Can be explained with a single activity driver" },
            { q: "43. An Activity-Based Costing, an inspection of the product is a \_\_\_\_ level activity:", o: ["Unit", "Batch", "Product", "Facility"], c: "Batch" },
            { q: "44. A company uses traditional standard costing system. The inspection and set-up costs are actually \u20b91,760 against a budget of \u20b92,000. ABC system is being implemented and accordingly the number of batches is identified as the cost driver for inspection and set up. The budgeted production is 10,000 units in batches of 1,000 units whereas actually 9,000 units were produced in 11 batches. The cost per batch under ABC system will be", o: ["160", "200", "180", "220"], c: "200" },
            { q: "45. X Company uses activity-based costing for Product B and Product D. The total estimated overhead cost for the parts administration activity pool was \u20b95,50,000 and the expected activity was 2000 part types. If Product D requires 1200 part types, the amount of overhead allocated to product D for parts administration would be:", o: ["2,75,000", "\u20b93,00,000", "\u20b93,30,000", "3,45,000"], c: "\u20b93,30,000" }
        ]
    },
    {
        setName: "Set 4",
        questions: [
            { q: "46. Fast Ltd. manufactures three types of products A, B, and C following ABC System. During a period, the company incurred \u20b973,000 as inspection cost and it was worked for 10, 20 and 9 production runs respectively for producing products A, B, and C. The inspection costs for product B under the ABC system was", o: ["15,000", "\u20b940,000", "18,000", "24,000"], c: "\u20b940,000" },
            { q: "47. A company operates an activity based costing (ABC) system to attribute its overhead costs to cost objects. In its budget for the year-ending 31st August, 2022. The company expected to place a total of 2000 purchase orders at a total cost of \u20b91,00,000. This activity and its related costs were budgeted to occur at a constant rate throughout the budget year which is divided into 13 four week periods. During the four-week period ended 30th June 2021, a total of 200 purchase orders were placed at a cost of \u20b99,000. The over recovery of these costs for the four-week period was", o: ["\u20b92,000", "\u20b93,000", "\u20b91,500", "\u20b91,000"], c: "\u20b91,000" },
            { q: "48. A company manufactures 500 units of product AX the material cost to manufacture is \u20b91,50,000, Labour cost \u20b92,65,000. Material reordering cost is \u20b94,500, Material handling cost is \u20b92,500 Material. order-35, Material movement-20. Total Material cost under Activity based costing is.", o: ["554", "4,22,000", "1,57,000", "1,084"], c: "1,57,000" },
            { q: "49. To obtain the break-even point in rupee sales value, total fixed costs are divided by:", o: ["Variable cost per unit;", "Contribution margin per unit;", "Fixed cost per unit;", "Profit/volume ratio."], c: "Profit/volume ratio." },
            { q: "50. The break-even point is the point at which:", o: ["There is no profit, no loss:", "Contribution margin is equal to total fixed cost:", "Total revenue is equal to total cost;", "All of the above."], c: "All of the above." },
            { q: "51. The primary difference between a fixed budget and a variable (flexible) budget is that a fixed budget:", o: ["includes only fixed costs, while a variable budget includes only variable costs.", "is concerned with only further acquisitions of fixed costs, while a variable budget is concerned with expenses which vary with sales.", "cannot be changed after the period begins, while a variable budget can be changed after the period begins.", "is a plan for a single level of sales (or other measure of activity), while a variable budget consists of several plans, one for each of several levels of sales (or other measures of activity)."], c: "is a plan for a single level of sales (or other measure of activity), while a variable budget consists of several plans, one for each of several levels of sales (or other measures of activity)." },
            { q: "52. Margin of safety is referred to as:", o: ["Excess of actual sales over fixed expenses;", "Excess of actual sales over variable expenses;", "Excess of actual sales over break-even sales:", "Excess of budgeted sales over fixed costs."], c: "Excess of actual sales over break-even sales;" },
            { q: "53. Contribution margin is known as", o: ["Marginal income", "Gross profit", "Net income", "Net profit"], c: "Marginal income" },
            { q: "54. Fixed cost per unit decrease when", o: ["Production volume increases", "Production volume decreases", "Variable costs per unit decreases", "Prime costs per unit decreases"], c: "Production volume increases" },
            { q: "55. Within a relevant range, the amount of variable costs per unit", o: ["Differs at each production level", "Remains constant at each production level", "Increases as production increases", "Decreases as production increases"], c: "Remains constant at each production level" },
            { q: "56. Margin of safety is referred to as", o: ["Excess of budgeted or actual sales over the variable expenses and fixed expense, at break-even.", "Excess of budgeted or actual sales revenue over the fixed expenses.", "Excess of actual sales over budgeted sales.", "Excess of sales revenue over the variable expenses"], c: "Excess of actual sales over budgeted sales." },
            { q: "57. Under marginal costing system, the contribution margin discloses the excess of", o: ["Revenue over fixed costs", "Projected revenues over the break-even point", "Revenues over variable costs", "Variable costs over fixed costs"], c: "Revenues over variable costs" },
            { q: "58. A decrease in sales price", o: ["does not affect the break-even point", "lowers the fixed cost", "Increases the break-even point", "lowers the break-even point"], c: "Increases the break-even point" },
            { q: "59. Determine Margin of safety if Profit is \u20b915,000 and P/V ratio is 40%.", o: ["37,500", "33,000", "38,000", "None of the above"], c: "37,500" },
            { q: "60. What is Margin of Safety if Sales is 20,000 units and B.E.P is 15,000 units?", o: ["15000 units", "5000 units", "10000 units", "20000 units"], c: "5000 units" }
        ]
    },
    {
        setName: "Set 5",
        questions: [
            { q: "61. Determine sales in rupees for desired profit if fixed cost is \u20b910,000, Variable cost is \u20b930,000, Sales is \u20b950,000 and desired profit is \u20b95,000.", o: ["73,500", "\u20b975,000", "\u20b95,000", "37,500"], c: "37,500" },
            { q: "62. What will be sales in rupees for desired profit if fixed cost is \u20b930,000, desired profit is \u20b915,000 and P/V ratio is 30%?", o: ["\u20b91,50,000", "\u20b91,00,000", "\u20b92,00,000", "None of the above"], c: "\u20b91,50,000" },
            { q: "63. Calculate sales in rupees for desired profit if fixed cost is \u20b910,000, selling price is \u20b920 per unit, Variable cost is \u20b915 per unit and desired profit is \u20b91 per unit", o: ["\u20b920,000", "50,000", "70,000", "\u20b910,000"], c: "50,000" },
            { q: "64. Determine sales in units for desired profit if Fixed cost is \u20b915,000, desired profit is \u20b95,000 Selling price per unit is \u20b920 and Variable cost per unit is \u20b916.", o: ["25,000 units", "5,000", "\u20b910,000", "10,000 units"], c: "25,000 units" },
            { q: "65. What will be sales in units if fixed cost is \u20b950,000 Contribution per unit is \u20b960 and desired profit per unit is \u20b910.", o: ["26,000 units", "1,000", "1,000 units", "6,000"], c: "1,000 units" },
            { q: "66. 9. Determine B.E.P in units and amount if Units produced if \u20b910,000, Fixed cost is \u20b940,000, Selling price is \u20b950 per unit and Variable cost us \u20b930 per unit.", o: ["240 per unit, \u20b92,00,000", "250 per unit, \u20b910,00,000", "220 per unit, \u20b91,00,000", "None of the above"], c: "220 per unit, \u20b91,00,000" },
            { q: "67. Determine B.E.P if Sales is \u20b91,00,000, Variable cost is \u20b950,000 and Profit is \u20b920,000.", o: ["60,000", "40,000", "\u20b980,000", "None of the above"], c: "60,000" },
            { q: "68. Pv ratio will increase if there is -", o: ["la decrease in fixed cost", "an increase in fixed cost", "a decrease in selling price per unit", "a decrease in variable cost per unit"], c: "a decrease in variable cost per unit" },
            { q: "69. Under marginal costing the cost of product for inventory valuation includes", o: ["prime costs and variable factory overheads", "prime cost only", "prime costs and Fixed factory overheads", "prime costs and all factory overheads"], c: "prime costs and variable factory overheads" },
            { q: "70. period costs are:", o: ["variable cost", "fixed cost", "prime cost", "overheads cost"], c: "fixed cost" },
            { q: "71. Marginal costs is taken as equal to", o: ["Prime Cost plus all variable overheads", "Prime Cost minus all variable overheads", "Variable overheads", "None of the above"], c: "Prime Cost plus all variable overheads" },
            { q: "72. Contribution margin is equal to", o: ["Sales - Fixed Cost - Profit", "Profit + Variable Cost", "Fixed Cost + Loss", "None of the above"], c: "Fixed Cost + Loss" },
            { q: "73. It is pallned sell 1,00,000 units of product A at \u20b912 per unit. Fixed Costs are \u20b92,80,000. To achive a profit of \u20b92,00,000 what would the variable costs be?", o: ["4,80,000", "7,20,000", "\u20b99,00,000", "\u20b99,20,000"], c: "7,20,000" },
            { q: "74. Factors which can change the break even point", o: ["change in total fixed costs", "change in variable costs per unit", "change in the selling price per unit", "All of the above."], c: "All of the above." },
            { q: "75. net profit ratio is 12% and bep is 40% of total sales compute pv ratio", o: ["60%", "52%", "28%", "20%"], c: "20%" }
        ]
    },
    {
        setName: "Set 6",
        questions: [
            { q: "76. If the total cost of 1000 units is \u20b960,000 and that of 1001 units is \u20b960,400, then the increase of \u20b9400 in the total cost is:", o: ["Prime cost", "All variable overheads", "Marginal cost", "None of the above"], c: "Marginal cost" },
            { q: "77. Which of the following statements are true about marginal costing?", o: ["In marginal costing, fixed costs are treated as product costs", "Marginal costing is not an independent system of costing", "The elements of cost in marginal costing are divided into fixed and variable components", "Both b and c"], c: "Both b and c" },
            { q: "78. The costing method where fixed factory overheads are added to inventory is called:", o: ["Activity-based costing", "Absorption costing", "Marginal costing", "All of the above"], c: "Absorption costing" },
            { q: "79. While computing profit in marginal costing:", o: ["The fixed cost gets added to the contribution", "The total marginal cost gets deducted from total sales revenue", "The total marginal cost gets added to total sales revenue", "None of the above"], c: "The total marginal cost gets deducted from total sales revenue" },
            { q: "80. Which of the following assumptions are made while calculating marginal cost", o: ["Total fixed cost is constant at all levels of output", "Total variable cost varies according to the volume of output", "All elements of cost can be divided into fixed and variable components", "All of the above."], c: "All of the above." },
            { q: "81. Contribution margin in marginal costing is also known as:", o: ["Net income", "Gross profit", "Marginal income", "None of the above"], c: "Marginal income" },
            { q: "82. What is the opportunity cost of making a component part in a factory given no alternative use of the capacity?", o: ["The variable manufacturing cost of the component", "The total manufacturing cost of the component", "The total variable cost of the component", "Zero"], c: "Zero" },
            { q: "83. The difference in total cost that results from two alternative courses of action is called:", o: ["Relevant Cost", "Opportunity Cost", "Differential Cost", "Marginal Cost"], c: "Differential Cost" },
            { q: "84. Relevant costs are:", o: ["unavoidable, future and measured by cash", "avoidable, future and measured by cash", "avoidable, future and measured by profit", "unavoidable, future and measured by profit"], c: "avoidable, future and measured by profit" },
            { q: "85. The profit at which total revenue is equal to the total cost is known as:", o: ["Margin of safety", "Break-even point", "Both a and b are incorrect", "Both a and b are correct"], c: "Break-even point" },
            { q: "86. Which of the following costs would not be accounted for in a company's recordkeeping system?", o: ["an unexpired cost", "an expired cost", "a product cost", "an opportunity cost"], c: "an opportunity cost" },
            { q: "87. PQR Ltd. manufactures a single product which it sells for \u20b940 per unit. Fixed cost is \u20b960,000 per year. The contribution to sales ratio is 40%. PQR Ltd.'s Break Even Point in units is", o: ["3500", "3700", "3750", "4000"], c: "3750" },
            { q: "88. The break-even point of a manufacturing company is \u20b91,60,000. Fixed cost is \u20b948,000. Variable cost is \u20b912 per unit. The PV ratio will be:", o: ["20%", "40%", "30%", "25%"], c: "30%" },
            { q: "89. Product A generates a contribution to sales ratio of 40%. Fixed cost directly attributable to Product A amounted to \u20b960,000. The sales revenue required to achieve a profit of \u20b915,000 is", o: ["\u20b92,00,000", "\u20b91,85,000", "\u20b91,87,500", "\u20b92,10,000"], c: "\u20b91,87,500" },
            { q: "90. XYZ Ltd. makes a special gadget for the car it manufactures. The machine for the gadget works to full capacity and incur \u20b915 Lakhs and \u20b940 Lakhs respectively as Variable and Fixed Costs. If all the gadgets were purchased from an outside supplier, the machine could be used to produce other items, which would earn a total contribution of \u20b925 Lakhs. What is the maximum price that XYZ Ltd. should be willing to pay to the outside supplier for the gadgets, assuming there is no change in Fixed Costs?", o: ["\u20b940 Lakhs", "\u20b965 Lakhs", "\u20b925 Lakhs", "\u20b915 Lakhs"], c: "\u20b940 Lakhs" }
        ]
    },
    {
        setName: "Set 7",
        questions: [
            { q: "91. X Ltd. has 1000 units of an obsolete item which are carried in inventory at the original price of \u20b950,000. If these items are reworked for \u20b920,000, they can be sold for \u20b936,000. Alternatively, they can be sold as a scrap for \u20b96,000 in the market. In a decision model used to analyze the reworking proposal, the opportunity cost should be taken as", o: ["16,000", "6,000", "\u20b930,000", "20,000"], c: "6,000" },
            { q: "92. The sales and profit of a firm for the year 2021 are \u20b91,50,000 and \u20b920,000 and for the year 2022 are \u20b91,70,000 and \u20b925,000 respectively. The P/V Ratio of the firm is", o: ["15%", "20%", "25%", "30%"], c: "25%" },
            { q: "93. Which one of the following is not considered as a method of Transfer Pricing", o: ["Negotiated Transfer Pricing", "Market Price Based Transfer Pricing", "Fixed Cost Based Transfer Pricing", "Opportunity Cost Based Transfer Pricing"], c: "Fixed Cost Based Transfer Pricing" },
            { q: "94. Method of pricing, when two separate pricing methods are used to price transfer of products from one subunit to another, is called:", o: ["Functional pricing", "Dual pricing", "Congruent pricing", "Optimal pricing"], c: "Functional pricing" },
            { q: "95. The Eastern division sells goods internally to the Western division of the same company. The quoted external price in industry publications from a supplier near Eastern is \u20b9200 per ton plus transportation. It costs \u20b920 per ton to transport the goods to Western. Eastern's actual market cost per ton to buy the direct materials to make the transferred product is \u20b9100. Actual per ton direct labour is \u20b950. Other actual costs of storage and handling are \u20b940. The company president selects a \u20b9220 transfer price. This is an example of:", o: ["Negotiated transfer pricing.", "Cost plus 20% transfer pricing.", "Cost-based transfer pricing.", "Market-based transfer pricing."], c: "Market-based transfer pricing." },
            { q: "96. Division P transfers its output to Division Q at variable cost. Once a year P charges a fixed fee to Q, representing an allowance for P's fixed costs. This type of transfer pricing system is commonly known as:", o: ["Dual pricing", "Negotiated transfer pricing", "Opportunity cost based transfer pricing", "Two-part tariff transfer pricing"], c: "Two-part tariff transfer pricing" },
            { q: "97. In which of the following circumstances is there a strong argument that profit centre accounting is a waste of time?", o: ["When the transferred item is also sold on an external market", "When the supplying division is based in a different country to head office", "If the transferred item is a major product of the supplying division", "If there is no similar product sold on an external market and the transferred item is a major product of the supplying division"], c: "If there is no similar product sold on an external market and the transferred item is a major product of the supplying division" },
            { q: "98. Which one of the following is not considered as a method of Transfer Pricing?", o: ["Negotiated Transfer Pricing", "Market Price Based Transfer Pricing", "Fixed Cost Based Transfer Pricing", "Opportunity Cost Based Transfer Pricing"], c: "Fixed Cost Based Transfer Pricing" },
            { q: "99. Method of pricing, when two separate pricing methods are used to price transfer of products from one subunit to another, is called:", o: ["dual pricing", "functional pricing", "congruent pricing", "optimal pricing"], c: "dual pricing" },
            { q: "100. M Group has two divisions, Division P and Division Q. Division P manufactures an item that is transferred to Division Q. The item has no external market and 6,000 units produced are transferred internally each year. The costs of each division are as follows? Variable Cost Division P \u20b9100 per unit Division Q \u20b9120 per unit Fixed cost each year \u20b91,20,000 \u20b990,000 Head Office management decided that a transfer price should be set that provides a profit of \u20b930,000 to Division P. What should be the transfer price per unit?", o: ["\u20b9145", "\u20b9125", "\u20b9120", "\u20b9135"], c: "\u20b9125" },
            { q: "101. Minimax Ltd. fixes inter - divisional transfer prices for its products on the basis of cost plus a return on investment in the division. The budget for division X for 2022-23 appears as under-Fixed Assets \u20b98,00,000 Current Assets \u20b95,00,000 Debtors \u20b92,00,000 Annual fixed cost of the division \u20b98,00,000 Variable cost per unit of the product \u20b910 Budgeted volume \u20b94,00,000 units per year Desired ROI 28%. Transfer price for division X is", o: ["13.05", "10.70", "8.70", "14.70"], c: "13.05" },
            { q: "102. BC Company fixes the interdivisional -transfer prices for its products on the basis of cost, plus a return on investment in the division. The Budget for Division for Alpha for the year 2021-22 appears as under: Fixed Assets \u20b95,00,000 Current assets \u20b93,00,000 Debtors \u20b92,00,000 Annual Fixed Cost of the Division \u20b98,00,000 Variable Cost per unit of Product \u20b910 Budgeted Volume 4,00,000 units per year Desired ROI 28% on \u20b910,00,000 Determine the transfer Price for Alpha.", o: ["12.7", "17.2", "27.1", "11.7"], c: "12.7" },
            { q: "103. The \_\_\_\_ method of transfer pricing was introduced in order to overcome the problems caused by using marginal cost", o: ["dual price", "Two-Part Transfer Pricing", "Negotiated Transfer Pricing", "none of them"], c: "dual price" },
            { q: "104. Transfer pricing methods may be classfied", o: ["under 3 pricing method", "under 4 pricing method", "under 5 pricing method", "under 7 pricing method"], c: "under 3 pricing method" },
            { q: "105. Which of the following is true of standards?", o: ["Standards represent a benchmark or a norm", "Standards relate to input quantity", "Standards relate to input cost", "All of the above"], c: "All of the above" }
        ]
    },
    {
        setName: "Set 8",
        questions: [
            { q: "106. Standards that can be attained only under the best circumstances are referred to as:", o: ["Attainable standards", "Budget standards.", "Ideal standards", "Practical standards"], c: "Ideal standards" },
            { q: "107. Who is most likely to be held responsible for a material price variance?", o: ["Line workers", "Production supervisors", "Purchasing managers", "Production schedulers"], c: "Purchasing managers" },
            { q: "108. Cost variance is the difference between", o: ["The standard cost and marginal cost", "The standards cost and budgeted cost", "The standards cost and the actual cost", "None of these"], c: "The standards cost and the actual cost" },
            { q: "109. Standard costing is a tool, which replaces the bottleneck of the \_\_\_\_ costing.", o: ["Present", "Future", "Historical", "None of the above"], c: "Historical" },
            { q: "110. If standard cost > actual, then it is:", o: ["Not favourable", "Favourable", "Neither favourable nor not favourable", "None of the above"], c: "Favourable" },
            { q: "111. From cost control point of view the standard most commonly used IS:", o: ["Expected standard", "Theoretical standard", "Normal standard", "Basic standard"], c: "Expected standard" },
            { q: "112. When more than one material is used in the manufacture of a product, which of the following variances arises:", o: ["Material yield variance", "Material mix variance", "Material price variance", "Material usage variance"], c: "Material mix variance" },
            { q: "113. Which of the following equations can be used to calculate a material quantity variance?", o: ["$(AQ\\times AP)-(AQ\\times SP)$", "$(AP\\times SP)-(AQ\\times SP)$", "$(AQ\\times SP)-(SQ\\times SP)$", "$(AQ\\times SP)-(AQ\\times AP)$"], c: "$(AQ\\times SP)-(SQ\\times SP)$" },
            { q: "114. Which of the following equations can be used to calculate a material price variance?", o: ["$(AQ\\times AP)-(AQ\\times SP)$", "$(AP\\times SP)-(AQ\\times SP)$", "$(AQ\\times SP)-(SQ\\times SP)$", "$(AQ\\times SP)-(AQ\\times AP)$"], c: "$(AQ\\times AP)-(AQ\\times SP)$" },
            { q: "115. Which of the following is not likely to be a reason of unfavourable direct labour efficiency variance?", o: ["Increase in direct materials prices", "Frequent break downs during production process", "Lack of proper supervision", "Use of old, outdated or faulty equipment"], c: "Increase in direct materials prices" },
            { q: "116. Which of the following is a purpose of standard costing?", o: ["To determine profit at different levels", "To determine break-even point", "To control costs", "To allocate cost with more accuracy"], c: "To control costs" },
            { q: "117. Which of the following activities is the Standard Costing System used for?", o: ["It is a basis for implementing cost control and fixing the price of products through variance analysis", "It helps to ascertain the cost-volume relationship between products manufactured by the business", "It helps to establish the breakeven point for the products manufactured by the company", "None of the above"], c: "It is a basis for implementing cost control and fixing the price of products through variance analysis" },
            { q: "118. Which of the following activities is true under the Standard Costing System?", o: ["The overhead volume variance is always beneficial", "The idle time variance is never favourable", "To calculate the overall costs, a company can either use budgetary control or standard costing but not both of those techniques", "The overhead efficiency variance plus overhead expense variance is equal to the overhead budget variance for variable overheads"], c: "The idle time variance is never favourable" },
            { q: "119. A standard cost is a carefully \_\_\_\_ unit cost which is prepared for each cost unit.", o: ["Pre-determined", "Absorbed", "Apportioned", "None"], c: "Pre-determined" },
            { q: "120. Setting of standard involves effective utilization of", o: ["Men", "Material", "Machines", "All of the above"], c: "All of the above" }
        ]
    },
    {
        setName: "Set 9",
        questions: [
            { q: "121. The standard cost card contains quantities and costs for", o: ["Direct material only", "Direct labour only", "Direct material and direct labour only", "Direct material, direct labour, and overhead"], c: "Direct material, direct labour, and overhead" },
            { q: "122. Standards differ from budgets in that:", o: ["Budgets but not standards may be used in valuing inventories", "Budgets but not standards may be journalized and posted", "Budgets are a total amount and standards are a unit amount", "Only budgets contribute to management planning and control"], c: "Budgets are a total amount and standards are a unit amount" },
            { q: "123. Standard Costs:", o: ["Are imposed by governmental agencies", "Are predetermined unit costs which companies use as measures of performance", "Can be used by manufacturing companies but not by service or not-for-profit companies", "All of the above"], c: "Are predetermined unit costs which companies use as measures of performance" },
            { q: "124. The advantages of standard costs include all of the following except:", o: ["Management by exception may be used", "Management planning is facilitated", "They may simplify the costing of inventories", "Management must use a static budget"], c: "Management must use a static budget" },
            { q: "125. Normal standards:", o: ["Allow for rest periods, machine breakdowns, and setup time", "Represent performance levels of under perfect operating conditions", "Are rarely used because managers believe they lower workforce morale", "Are more likely than ideal standards to result in unethical practices"], c: "Allow for rest periods, machine breakdowns, and setup time" },
            { q: "126. The setting of standards is:", o: ["A managerial accounting decision", "A management decision", "A worker decision", "Preferably set at the ideal level of performance"], c: "A management decision" },
            { q: "127. Which of the following is correct about the total overhead variance?", o: ["Budgeted overhead and budgeted overhead applied are the same", "Total actual overhead is composed of variable overhead, fixed overhead, and period costs.", "Standard hours actually worked are used in computing the variance", "Standard hours allowed for the work done is the measure used in computing the variance"], c: "Standard hours allowed for the work done is the measure used in computing the variance" },
            { q: "128. What is the name given to a budget that has been prepared by re-evaluating activities and comparing the incremental costs of those activities with their incremental benefits?", o: ["Incremental budget", "Rolling budget", "Zero based budget", "Flexible budget"], c: "Zero based budget" },
            { q: "129. A budget is an instrument of management used as an aid in the", o: ["Planning", "Programming", "Control of business activity", "All of the above"], c: "All of the above" },
            { q: "130. Following may be regarded as a summary budget", o: ["Production budget", "Master budget", "Cash budget", "Sales budget"], c: "Master budget" },
            { q: "131. Purchases budget is prepared using the information from:", o: ["Capital expenditure budget", "Materials budget", "Both (1) and (2)", "None of the above"], c: "Materials budget" },
            { q: "132. Following budget may be compiled on departmental basis:", o: ["Production budget", "Purchase budget", "Materials budget", "All of the above"], c: "Production budget" },
            { q: "133. Production budget is based upon:", o: ["Sales budget", "Factory capacity", "Availability of raw material and labour", "All of the above."], c: "All of the above." },
            { q: "134. Budget includes:", o: ["Income", "Expenditure", "Employment of capital", "All of the above"], c: "All of the above" },
            { q: "135. A budget should be:", o: ["Rigid", "Flexible", "Both (1) and (2)", "None of the above"], c: "Flexible" }
        ]
    },
    {
        setName: "Set 10",
        questions: [
            { q: "136. The object of budgetary control is", o: ["Planning", "Forecasting", "Organizing", "Directing"], c: "Planning" },
            { q: "137. The budget which is dynamic is", o: ["Flexible budget", "Sales budget", "Cash budget", "Purchase budget"], c: "Sales budget" },
            { q: "138. The process of budgeting helps in the control of:", o: ["Cost of production", "Liquidity", "Capital Expenditure", "All of the above"], c: "All of the above" },
            { q: "139. Plant utilization budget and Manufacturing overhead budgets are types of:", o: ["Production budget", "Sales budget", "Cost budget", "None of the above"], c: "Cost budget" },
            { q: "140. R&D budget and Capital expenditure budget are examples of:", o: ["Short-term budget", "Current budget", "Long-term budget", "None of the above"], c: "Long-term budget" },
            { q: "141. The scare factors is also known as:", o: ["Key factor", "Abnormal factor", "Linking factor", "None of the above"], c: "Key factor" },
            { q: "142. What is the name given to a budget that has been prepared by re-evaluating activities and comparing the incremental costs of those activities with their incremental benefits?", o: ["Incremental budget", "Rolling budget", "Zero based budget", "Flexible budget"], c: "Zero based budget" },
            { q: "143. A budget is an instrument of management used as an aid in the", o: ["Planning", "Programming", "Control of business activity", "All of the above"], c: "All of the above" },
            { q: "144. Following may be regarded as a summary budget", o: ["Production budget", "Master budget", "Cash budget", "Sales budget"], c: "Master budget" },
            { q: "145. Purchases budget is prepared using the information from:", o: ["Capital expenditure budget", "Materials budget", "Both (1) and (2)", "None of the above"], c: "Materials budget" },
            { q: "146. Following budget may be compiled on departmental basis:", o: ["Production budget", "Purchase budget", "Materials budget", "All of the above"], c: "Production budget" },
            { q: "147. Production budget is based upon:", o: ["Sales budget", "Factory capacity", "Availability of raw material and labour", "All of the above"], c: "All of the above" },
            { q: "148. A budget should be:", o: ["Rigid", "Flexible", "Both (1) and (2)", "None of the above"], c: "Flexible" },
            { q: "149. The object of budgetary control is", o: ["Planning", "Forecasting", "Organizing", "Directing"], c: "Planning" },
            { q: "150. The budget which is dynamic is", o: ["Flexible budget", "Sales budget", "Cash budget", "Purchase budget"], c: "Sales budget" }
        ]
    },
    {
        setName: "Set 11",
        questions: [
            { q: "151. The process of budgeting helps in the control of:", o: ["Cost of production", "Liquidity", "Capital Expenditure", "All of the above"], c: "All of the above" },
            { q: "152. Plant utilization budget and Manufacturing overhead budgets are types of:", o: ["Production budget", "Sales budget", "Cost budget", "None of the above"], c: "Cost budget" },
            { q: "153. R&D budget and Capital expenditure budget are examples of:", o: ["Short-term budget", "Current budget", "Long-term budget", "None of the above"], c: "Long-term budget" },
            { q: "154. The scare factors is also known as:", o: ["Key factor", "Abnormal factor", "Linking factor", "None of the above"], c: "Key factor" },
            { q: "155. A company usually determines the appropriate degree of decentralization based on a combination of the", o: ["Managers personal characteristics", "Nature of decisions required for organizational growth", "Types of organizational activities in which the company is engaged top management recognizes and develop managerial talent", "All of these"], c: "All of these" },
            { q: "156. Major disadvantages of Decentralization are", o: ["Can result in a lack of goal congruence or sub optimization by sub-unit managers", "Requires more effective communication abilities because decision making is removed from the home office", "Helps", "Both 1 and 2"], c: "Both 1 and 2" },
            { q: "157. Which of the following is/are not benefit/s of Decentralization?", o: ["Greater awareness of local problems", "Allows managerial performance to be comparatively evaluated", "Creates personnel difficulties upon introduction, especially if managers are unwilling to delegate effectively", "Develops skill level of junior managers"], c: "Creates personnel difficulties upon introduction, especially if managers are unwilling to delegate effectively" },
            { q: "158. Return on Equity =", o: ["Net Profit Margin x Asset Turnover Ratio x Financial Leverage", "Gross Profit Margin x Asset Turnover Ratio x Financial Leverage", "Net Profit Margin x Inventory Turnover Ratio x Financial Leverage", "Net Profit Margin x Asset Turnover Ratio / Operating Leverage"], c: "Net Profit Margin x Asset Turnover Ratio x Financial Leverage" },
            { q: "159. According to DuPont methodology, three main financial parameters that drive Return on Equity (ROE) are", o: ["(1) Employee performance, (2) Asset usage performance, and (3) Financial leverage.", "(1) Operating performance, (2) Asset usage performance, and (3) Financial leverage.", "(1) Operating performance, (2) Inventory usage performance, and (3) Financial leverage.", "(1) Operating performance, (2) Asset usage performance, and (3) Operating leverage."], c: "(1) Operating performance, (2) Asset usage performance, and (3) Financial leverage." },
            { q: "160. Asset usage performance means", o: ["a very basic profitability ratio", "Total Asset Turnover (Turnover / Total Assets)", "the use of debt to acquire additional assets or fund projects", "None of these"], c: "Total Asset Turnover (Turnover / Total Assets)" },
            { q: "161. Financial leverage means", o: ["a very basic profitability ratio", "Total Asset Turnover (Turnover / Total Assets)", "the use of debt to acquire additional assets or fund projects", "None of these"], c: "the use of debt to acquire additional assets or fund projects" },
            { q: "162. According to Du Pont Analysis a company can increase its Return on Equity if it", o: ["Generates a high Net Profit Margin", "Effectively uses its assets so as to generate more sales", "Has a high Financial Leverage", "All of these"], c: "All of these" },
            { q: "163. Du Pont ROE =", o: ["Margin on Sales x Asset Turnover x Equity Multiplier", "Margin of Safety x Asset Turnover x Equity Multiplier", "Margin on Sales x Inventory Turnover x Equity Multiplier", "Margin on Sales x Asset Turnover x Debt Multiplier"], c: "Margin on Sales x Asset Turnover x Equity Multiplier" },
            { q: "164. \_\_\_\_ expresses divisional profit as a percentage of the assets employed in the division.", o: ["ROI", "EPS", "ROCE", "EBITDA"], c: "ROI" },
            { q: "165. Return on investment (ROI) is", o: ["(Profit before tax / Operations management capital employed) x 100", "(Profit before interest and tax / Total capital employed) x 100", "(ROE / Operations management capital employed) x 100", "(Profit before interest and tax / Operations management capital employed) x 100"], c: "(Profit before interest and tax / Operations management capital employed) x 100" }
        ]
    },
    {
        setName: "Set 12",
        questions: [
            { q: "166. RI (Residual Income) =", o: ["Divisional profit - (Percentage of change in Sales \u00d7 Divisional investment)", "Divisional profit - (Percent capital charge \u00d7 Total investment)", "Divisional profit - (Percent capital charge \u00d7 Divisional investment)", "Total profit - (Percent capital charge \u00d7 Divisional investment)"], c: "Divisional profit - (Percent capital charge \u00d7 Divisional investment)" },
            { q: "167. The main advantages of RI is/are", o: ["It avoids suboptimal decisions as investments are not rejected merely because they lower the divisional manger's ROI.", "It maximizes growth of the company and increases shareholders' wealth by accepting opportunities which earn a rate of return in excess of the cost of capital.", "The cost of capital charge on divisional investments ensures that divisional managers are aware of the opportunity cost of funds.", "All of these"], c: "All of these" },
            { q: "168. Acme, a division of Ace Manufacturing, has assets of \u20b92,25,000 and an operating income of \u20b955,000. What is the division's ROI?", o: ["24.44%", "23%", "25%", "50%"], c: "24.44%" },
            { q: "169. An investment centre has net assets of \u20b98,00,000, and made profits before interest and tax of \u20b91,60,000. The notional cost of capital is 12%. Calculate and comment on the RI (Residual Income) for the period.", o: ["1,60,000", "96,000", "64,000", "2,56,000"], c: "64,000" },
            { q: "170. A person made a Capital Investment of \u20b92,00,000 in a company. Operating profit, after taxes, is \u20b928,000. The opportunity cost of that investment is 10%, Calculate EVA.", o: ["20,000", "2,800", "\u20b98,000", "17,200"], c: "\u20b98,000" },
            { q: "171. For EVA there 3 responsibility centres, which are", o: ["Cost centre", "Profit centre", "Investment centre", "All of these"], c: "All of these" },
            { q: "172. The theory of learning curves will only hold if which of the following conditions apply?", o: ["The task must be repetitive", "Production must be at an early stage so that there is room for improvement", "There is inconsistency in the workforce", "Both 1 and 2"], c: "Both 1 and 2" },
            { q: "173. \_\_\_\_ can be used: a. To calculate the incremental cost of making extra units of a particular products, b. To set standards for labour. c. To prepare realistic production budgets and to report labour cost variances, and d. To quote contact price.", o: ["Learning curve theory", "Return on investment", "Du Pont ROE", "Economic Value Added"], c: "Learning curve theory" },
            { q: "174. The four Perspectives of the Balanced Scorecard are", o: ["1. Operational Perspective, 2. Customers Perspective, 3. Internal business process Perspective and 4. Learning & Growth Perspectives.", "1. Financial Perspective, 2. Sellers Perspective, 3. Internal business process Perspective and 4. Learning & Growth Perspectives.", "1. Financial Perspective, 2. Customers Perspective, 3. Internal business process Perspective and 4. Learning & Growth Perspectives.", "1. Financial Perspective, 2. Customers External process Perspective and 4. Learning & Growth Perspectives."], c: "1. Financial Perspective, 2. Customers Perspective, 3. Internal business process Perspective and 4. Learning & Growth Perspectives." },
            { q: "175. MI Ltd. has earned a net profit of \u20b915 lakhs after Tax at 30%. Interest cost charged by the financial institutions was \u20b910 Lakhs. The Invested capital is \u20b995 Lakhs of which 55% is debt. The company maintains a weighted average cost of capital of 13%. Compute the Operating Income.", o: ["15 lakhs", "21.43 lakhs", "10 lakhs", "31.43 lakhs"], c: "31.43 lakhs" },
            { q: "176. According to Kaplan & Norton, which of the balanced scorecard perspectives serves as the focus of the other perspectives?", o: ["Financial.", "Customer.", "Internal business processes.", "Learning & growth."], c: "Financial." },
            { q: "177. 4. Which of the following would be considered an operating asset in return on investment computations?", o: ["Land being held for plant expansion.", "Treasury stock.", "Accounts receivable.", "Common stock."], c: "Accounts receivable." },
            { q: "178. A company that is seeking to increase ROI should attempt to decrease:", o: ["Sales.", "Turnover.", "Margin.", "Average operating assets."], c: "Average operating assets." },
            { q: "179. The performance of investment centre is based on", o: ["Cost of the centre", "Profit of the centre", "Profit and investment of the centre", "Revenue of the centre"], c: "Profit and investment of the centre" },
            { q: "180. Both costs and revenues are measured in \_\_\_\_ centers", o: ["Cost", "Profit", "Revenue", "All of these"], c: "Profit" }
        ]
    },
    {
        setName: "Set 13",
        questions: [
            { q: "181. A cost centre is a segment of the organization where the manager is responsible for", o: ["Costs", "Inputs", "A or B", "None of these"], c: "A or B" },
            { q: "182. The performance of investment centre is based on", o: ["Cost of the centre", "Profit of the centre", "Profit and investment of the centre", "Revenue of the centre"], c: "Profit and investment of the centre" },
            { q: "183. Responsibility accounting is used for", o: ["cost control", "planning", "decision making", "pricing"], c: "cost control" },
            { q: "184. Responsibility Accounting is also known as", o: ["Profitability accounting", "Activity accounting", "Both A and B", "None of the above"], c: "Both A and B" },
            { q: "185. Which of the following characteristics is not associated with traditional responsibility accounting?", o: ["Assumes optimization of the parts will optimize the whole.", "Assumes independence of the parts.", "Places emphasis on the performance of lindividuals.", "Attempts to control processes."], c: "Attempts to control processes." },
            { q: "186. In responsibility accounting, responsibilities of various groups or individuals are identified in terms of", o: ["Work", "Revenue", "Cost", "All of the above"], c: "All of the above" },
            { q: "187. The area of focus on responsibility center IS", o: ["Quantum of sales", "Quantum of production", "Optimum utilization of resources", "All of the above"], c: "Optimum utilization of resources" },
            { q: "188. In profit center revenue represents a monetary measure of output emanating from a profit center in a given period irrespective whether", o: ["sales revenue is realized or not", "The output is sold or not", "Both A and B", "None of the above"], c: "Both A and B" },
            { q: "189. In a control report of Department X, it is mentioned as indirect materials are \u20b91,000, indirect labour \u20b9900, Overtime Charges \u20b9100, Depreciation on equipment \u20b9500, Allocated factory overhead (38% of factory space) \u20b94,300, Allocated overhead of repair shop is \u20b91,200. Determine total costs treating department X as a responsibility center.", o: ["3,200", "2,200", "1,200", "None of the above"], c: "3,200" },
            { q: "190. Which of the following criterion is not used for decision-making under uncertainty?", o: ["Maximin", "Maximax", "Minimax", "Minimize expected loss"], c: "Minimize expected loss" },
            { q: "191. Decision theory is concerned with", o: ["Methods of arriving at an optimal decision", "Selecting optimal decision in a sequential manner", "Analysis of information that is available", "All of these"], c: "All of these" },
            { q: "192. Which of the following criterion is not applicable to decision-making under risk?", o: ["Maximize expected return", "Maximize return", "Minimize expect regret", "Knowledge of likelihood occurrence of each state of nature"], c: "Maximize return" },
            { q: "193. The minimum expected opportunity loss (EOL) is", o: ["Equal to EVPI", "Minimum regret", "Equal to EMV", "Both (A) and (B)"], c: "Both (A) and (B)" },
            { q: "194. The expected value of perfect information (EVPI) is", o: ["Equal to expected regret of the optimal decision under risk", "The utility of additional information", "Maximum expected opportunity loss", "None of the above"], c: "Equal to expected regret of the optimal decision under risk" },
            { q: "195. The value of the coefficient of optimism $(\\alpha)$ is needed while using the criterion of", o: ["Equally likely", "Maximin", "Realism", "Minimax"], c: "Realism" }
        ]
    },
    {
        setName: "Set 14",
        questions: [
            { q: "196. The decision-maker's knowledge and experience may influence the decision-making process when using the criterion of", o: ["Maximax", "Maximax regret", "Realism", "Maximin"], c: "Realism" },
            { q: "197. The difference between the expected profit under conditions of risk and the expected profit with perfect information is called", o: ["The expected value of perfect information", "Expected marginal loss", "None of the above", "Any one of the above"], c: "The expected value of perfect information" },
            { q: "198. A situation in which a decision maker knows all of the possible outcomes of a decision and also knows the probability associated with each outcome is referred to as", o: ["Certainty.", "Risk.", "Uncertainty.", "Strategy."], c: "Risk." },
            { q: "199. Which of the following methods of selecting a strategy is consistent with risk averting behaviour?", o: ["If two strategies have the same expected profit, select the one with the smaller standard deviation.", "If two strategies have the same standard deviation, select the one with the smaller expected profit.", "Select the strategy with the larger coefficient of variation.", "All of the above are correct."], c: "If two strategies have the same expected profit, select the one with the smaller standard deviation." },
            { q: "200. Which one of the following does not measure risk?", o: ["Coefficient of variation", "Standard deviation", "LPP", "All of the above are measures of risk."], c: "LPP" },
            { q: "201. The sequence of possible managerial decisions and their expected outcome under each set of circumstances can be represented and analysed by using", o: ["The minimax regret criterion.", "A decision tree.", "A payoff matrix.", "Simulation."], c: "A decision tree." },
            { q: "202. We are comparing two investment projects. Both have expected returns of 20%, but the standard deviation of Project A's returns is 15%, while the standard deviation of Project B's returns is 9%. Which one is relatively riskier?", o: ["A", "B", "Both A and B", "Bnone of these"], c: "A" },
            { q: "203. Two investments have different expected returns. Project A's expected return is 20% and the standard deviation of its returns is 15%. Project B's expected return is only 10%, while the standard deviation of its returns remains at 9%. Compute Coefficient of Varience of Project A.", o: ["0.20", "0.75", "0.90", "0.10"], c: "0.75" },
            { q: "204. Which of the following is NOT a characteristic of management accounting?", o: ["Future-oriented", "Subjective in nature", "Mandatory as per law", "Useful for internal decision-making"], c: "Mandatory as per law" },
            { q: "205. Management accounting reports are primarily intended for:", o: ["Government authorities", "External shareholders", "Internal management", "Credit rating agencies"], c: "Internal management" },
            { q: "206. A key feature of management accounting is that it:", o: ["Provides real-time data for decisions", "Follows GAAP strictly", "Is audited annually", "Is used only by external parties"], c: "Provides real-time data for decisions" },
            { q: "207. The technique used in management accounting to compare actual results with planned performance is:", o: ["Ledger balancing", "Trial balance preparation", "Variance analysis", "Cash accounting"], c: "Variance analysis" },
            { q: "208. In Activity Based Costing, the first step is to:", o: ["Determine cost pools", "Select cost drivers", "Identify activities", "Allocate overheads to cost objects"], c: "Identify activities" },
            { q: "209. Which of the following is least suitable as a cost driver under ABC?", o: ["Number of machine setups", "Direct labour hours", "Number of customer orders", "Total factory square footage"], c: "Total factory square footage" },
            { q: "210. A company has identified the following overhead cost pools and cost drivers for a product: Setup cost pool: \u20b92,00,000; driver = number of setups (2,500 setups) Inspection cost pool: \u20b91,00,000; driver = number of inspections (50,000 inspections) Product X has 200 setups and 4,000 inspections. What is the overhead allocated to Product X (using ABC)?", o: ["16,000", "12,000", "24,000", "14,000"], c: "24,000" }
        ]
    },
    {
        setName: "Set 15",
        questions: [
            { q: "211. A product requires 5 machine hours. The machine hour activity pool has \u20b93,00,000 budgeted cost and 15,000 machine hours. What is the machine-hour overhead allocated to that product under ABC?", o: ["\u20b9100", "\u20b9500", "\u20b91,000", "\u20b92,000"], c: "\u20b91,000" },
            { q: "212. A firm has two products A and B. The \"order processing\" cost pool is \u20b91,20,000. The cost driver is number of orders. There are 2,000 orders in total: A uses 600 orders; B uses 1,400 orders. The overhead assigned to B is:", o: ["89,000", "84,000", "48,000", "\u20b970,000"], c: "84,000" },
            { q: "213. A company currently uses traditional costing and absorbs overheads at \u20b920 per direct labour hour. Under ABC, two cost pools are identified: Setups (\u20b950,000) with driver number of setups (500), and material handling (\u20b91,00,000) with driver number of parts (2,00,000). Product Y uses 50 setups and 4,000 parts. Under ABC, overhead allocated to Y is:", o: ["10,000", "7,000", "14,000", "12,000"], c: "7,000" },
            { q: "214. A company incurs \u20b960,000 as facility-sustaining cost (which supports all products), and allocates it equally across 3 product lines X, Y, Z under ABC. Product X produces 5,000 units, Y 10,000 units, Z 15,000 units. What is the per-unit share of facility cost for Z?", o: ["\u20b94", "\u20b92", "\u20b91.50", "\u20b91.33"], c: "\u20b91.33" },
            { q: "215. Which statement is true about ABC compared to traditional absorption costing?", o: ["ABC tends to under-cost high volume products and over-cost low volume products", "ABC always leads to lower cost per unit estimates", "ABC ignores overhead costs that are fixed", "ABC is simpler to implement than traditional costing"], c: "ABC tends to under-cost high volume products and over-cost low volume products" },
            { q: "216. In ABC, \"facility-sustaining costs\" are:", o: ["Costs that vary with every unit produced", "Costs that support the entire facility but cannot be traced to individual products", "Always variable costs", "Never included in costing"], c: "Costs that support the entire facility but cannot be traced to individual products" },
            { q: "217. Under ABC, if an activity's cost is zero (i.e., no cost incurred), then:", o: ["Its cost driver rate is infinite", "Its cost driver rate is zero", "It is automatically merged with another pool", "It must still be assigned across products"], c: "Its cost driver rate is zero" },
            { q: "218. A \"cost pool\" in ABC refers to:", o: ["A grouping of fixed costs only", "A set of overhead costs associated with a specific activity", "The sum of direct costs in a department", "The total cost of all drivers"], c: "A set of overhead costs associated with a specific activity" },
            { q: "219. Which of the following is not an assumption of marginal costing?", o: ["Costs can be separated into fixed and variable components", "Variable cost per unit remains constant over the relevant range", "Selling price per unit changes with volume", "No change in inventory level"], c: "Selling price per unit changes with volume" },
            { q: "220. When there are no inventories, profit under marginal costing and absorption costing will be:", o: ["The same", "Different", "Marginal costing profit greater", "Absorption costing profit greater"], c: "The same" },
            { q: "221. Under marginal costing, get-or-drop decisions predominantly rely on:", o: ["Fixed cost recovery", "Contribution margin", "Full cost per unit", "Absorbed fixed overhead"], c: "Contribution margin" },
            { q: "222. Which statement is true?", o: ["Marginal costing is a complete costing system", "Marginal costing is only a technique of cost analysis", "Marginal costing always gives higher profit than absorption costing", "Marginal costing never considers fixed cost"], c: "Marginal costing is only a technique of cost analysis" },
            { q: "223. What happens to fixed cost per unit when production increases?", o: ["It remains constant", "It increases", "It decreases", "It becomes zero"], c: "It decreases" },
            { q: "224. If the P/V ratio increases, what happens to the break-even point (in rupees)?", o: ["It increases", "It decreases", "It remains unchanged", "Cannot determine"], c: "It decreases" },
            { q: "225. Which decision is least appropriate based on marginal costing?", o: ["Accepting a special order at a lower price", "Make vs buy decision", "Product mix under limited capacity", "Long-term pricing for strategic positioning"], c: "Long-term pricing for strategic positioning" }
        ]
    },
    {
        setName: "Set 16",
        questions: [
            { q: "226. The difference in profit between absorption and marginal costing arises due to:", o: ["Different sales levels", "Different treatments of variable cost", "Inventory valuation differences", "Treatment of direct labor"], c: "Inventory valuation differences" },
            { q: "227. Under marginal costing, closing stock is valued at:", o: ["Full cost (direct + variable + fixed overhead)", "Variable cost per unit", "Replacement cost", "Market price"], c: "Variable cost per unit" },
            { q: "228. A company is operating at 80% capacity. A special order is received for 1,000 units at \u20b9120 each. Variable cost is \u20b990 per unit. Should the order be accepted?", o: ["No, price is too low", "Yes, contribution is \u20b930 per unit", "No, fixed cost will increase", "Yes, fixed cost is saved"], c: "Yes, contribution is \u20b930 per unit" },
            { q: "229. A product yields a contribution of \u20b960 per unit. A customer offers \u20b9500 per unit for 50 extra units. Variable cost per unit is \u20b9440. Should the offer be accepted?", o: ["No, price is too low", "Yes, contribution is positive", "Only if fixed cost decreases", "Yes, profit is \u20b960 per unit"], c: "Yes, contribution is positive" },
            { q: "230. The variable cost of a product is \u20b950, and fixed cost per unit is \u20b930. There is idle capacity. What is the transfer price under marginal costing?", o: ["\u20b950.", "\u20b980", "\u20b930", "\u20b90"], c: "\u20b950." },
            { q: "231. A division can sell its product in the open market at \u20b9100. The variable cost is \u20b960. What should be the minimum transfer price if the division is at full capacity?", o: ["\u20b960", "\u20b970", "\u20b980", "\u20b9100"], c: "\u20b9100" },
            { q: "232. A division has 1,000 units of idle capacity. Variable cost per unit \u20b945. It can transfer units to another division or sell externally for \u20b960. What is the opportunity cost of internal transfer?", o: ["\u20b960", "\u20b915", "\u20b945", "\u20b90"], c: "\u20b90" },
            { q: "233. If the selling division is working at full capacity and transfers internally at marginal cost, the likely impact is:", o: ["Division earns profit", "Division incurs loss", "Division loses external contribution", "No impact on profit"], c: "Division loses external contribution" },
            { q: "234. A buying division is offered a component internally at \u20b970. External market price is \u20b965. Should it buy internally if internal cost is \u20b950?", o: ["Yes, \u20b970 is better", "No, market price is lower", "Yes, internal cost is lower than market", "No, fixed cost is not recovered"], c: "No, market price is lower" },
            { q: "235. Selling Division: $VC=\u20b935$, External Price \u20b950. Internal Transfer Price \u20b935. If 1,000 units are transferred, what is total opportunity cost?", o: ["\u20b920", "35,000", "15,000", "50,000"], c: "15,000" },
            { q: "236. A company has fixed costs of \u20b950,000 and variable costs of \u20b920 per unit. Selling price is \u20b950 per unit. What is the break-even sales in units?", o: ["1,250", "2,500", "3,333", "1,667"], c: "1,667" },
            { q: "237. In marginal costing, profit is maximum when:", o: ["Marginal cost equals marginal revenue", "Contribution equals fixed cost", "Fixed cost equals variable cost", "Total cost equals total revenue"], c: "Marginal cost equals marginal revenue" },
            { q: "238. Which of the following is a correct reason to accept a special order in marginal costing?", o: ["It results in positive contribution", "It increases fixed costs", "It reduces P/V ratio", "It affects stock value"], c: "It results in positive contribution" },
            { q: "239. In make-or-buy decisions using marginal costing, which cost is always relevant?", o: ["Allocated head office expenses", "Sunk cost", "Variable production cost", "Apportioned rent"], c: "Variable production cost" },
            { q: "240. A division transfers goods internally at marginal cost. What is a key disadvantage?", o: ["Overstatement of division's profit", "Under-recovery of fixed costs", "Double counting of variable cost", "Increased total cost"], c: "Under-recovery of fixed costs" }
        ]
    },
    {
        setName: "Set 17",
        questions: [
            { q: "241. Which decision is most appropriate to use marginal costing?", o: ["Choosing depreciation method", "Selecting supplier for raw material", "Adding a new product line under capacity", "Evaluating internal audit risk"], c: "Adding a new product line under capacity" },
            { q: "242. When marginal cost equals transfer price, the transferring division will likely:", o: ["Make excess profit", "Break even", "Show zero contribution", "Lose incentive to transfer"], c: "Lose incentive to transfer" },
            { q: "243. If internal transfers are made at marginal cost, which division may feel disadvantaged?", o: ["Buying division", "Corporate center", "Selling division", "Marketing department"], c: "Selling division" },
            { q: "244. Sales \u20b95,00,000, variable costs $=\u20b93,00,000$ fixed costs = \u20b91,00,000. What is margin of safety?", o: ["\u20b91,00,000", "2,50,000", "1,25,000", "\u20b950,000"], c: "2,50,000" },
            { q: "245. Fixed cost \u20b980,000, break-even sales $\u20b92,00,000$. If sales rise to \u20b93,00,000, what is profit?", o: ["\u20b920,000", "\u20b940,000", "\u20b960,000", "\u20b980,000"], c: "\u20b940,000" },
            { q: "246. A firm produces 5,000 units at total cost \u20b91,50,000; at 6,000 units, total cost \u20b91,70,000. Marginal cost per unit?", o: ["\u20b920", "\u20b940", "\u20b925", "\u20b930"], c: "\u20b920" },
            { q: "247. A company gets a special order of 2,000 units at \u20b945 each. Variable cost is \u20b940. Fixed costs remain the same. Should the order be accepted?", o: ["Yes, gives \u20b910,000", "No, below cost", "Yes, covers FC", "No. loss"], c: "Yes, gives \u20b910,000" },
            { q: "248. Product A: SP \u20b9100, VC \u20b970 (2 hrs); B: SP \u20b980, VC \u20b950 (1 hr); 5,000 hrs available. What to produce?", o: ["All A", "All B", "Mix", "None"], c: "All B" },
            { q: "249. A company has the following standards: 5 kg of material at \u20b910/kg. Actual usage was 6 kg at \u20b99/kg. What is the Material Price Variance?", o: ["\u20b96 Favorable", "\u20b96 Adverse", "\u20b910 Favorable", "\u20b910 Adverse"], c: "\u20b96 Favorable" },
            { q: "250. If the standard labor time for 100 units is 200 hours and the actual hours taken are 220 hours at a standard wage rate of \u20b950 per hour, what is the labor efficiency variance?", o: ["\u20b91000 Favorable", "\u20b91000 Adverse", "\u20b9500 Favorable", "\u20b9500 Adverse"], c: "\u20b91000 Adverse" },
            { q: "251. A product's standard cost includes 3 hours of labor at \u20b940 per hour. Actual labor was 4 hours at \u20b938 per hour. What is the labor rate variance?", o: ["\u20b98 Favorable", "\u20b98 Adverse", "\u20b9120 Favorable", "\u20b9120 Adverse"], c: "\u20b98 Favorable" },
            { q: "252. Standard cost of variable overhead is \u20b95 per hour. Standard hours allowed for actual production are 1000 hours, actual hours worked are 1100 hours, and actual overhead is \u20b95600. Calculate variable overhead spending variance.", o: ["\u20b9100 Favorable", "\u20b9100 Adverse", "\u20b9600 Favorable", "\u20b9600 Adverse"], c: "\u20b9100 Adverse" },
            { q: "253. A company produces 500 units. The standard material per unit is 2 kg at \u20b94 per kg. Actual material used is 1100 kg at \u20b93.8 per kg. Calculate material usage variance.", o: ["\u20b9200 Favorable", "\u20b9200 Adverse", "\u20b9400 Favorable", "\u20b9400 Adverse"], c: "\u20b9400 Adverse" },
            { q: "254. A company's fixed overhead absorption rate is \u20b910 per hour. Standard hours allowed for actual production are 500 hours. Actual fixed overhead incurred was \u20b95200. Calculate fixed overhead spending variance.", o: ["\u20b9200 Adverse", "\u20b9200 Favorable", "\u20b9700 Adverse", "\u20b9700 Favorable"], c: "\u20b9200 Adverse" },
            { q: "255. Standard variable overhead rate is \u20b94 per hour. Standard hours allowed are 500 hours. Actual hours worked are 550 hours and actual variable overhead is \u20b92300. Calculate variable overhead efficiency variance.", o: ["\u20b9200 Adverse", "\u20b9200 Favorable", "\u20b9100 Adverse", "\u20b9100 Favorable"], c: "\u20b9200 Adverse" }
        ]
    },
    {
        setName: "Set 18",
        questions: [
            { q: "256. Which variance arises due to the difference between actual price and standard price of materials?", o: ["Material Usage Variance", "Material Price Variance", "Labor Efficiency Variance", "Overhead Variance"], c: "Material Price Variance" },
            { q: "257. Labour efficiency variance indicates:", o: ["The difference between actual and standard wages", "The difference between actual hours and standard hours for actual production", "The difference between actual and budgeted production", "The difference between actual and standard price of labor"], c: "The difference between actual hours and standard hours for actual production" },
            { q: "258. Which of the following is a favorable variance?", o: ["Actual cost more than standard cost", "Actual cost less than standard cost", "Actual output less than standard output", "Standard cost more than actual cost"], c: "Actual cost less than standard cost" },
            { q: "259. Overhead variances are classified into:", o: ["Fixed and Variable overhead variances", "Material and Labour overhead variances", "Efficiency and Price variances only", "Selling and Administrative variances"], c: "Fixed and Variable overhead variances" },
            { q: "260. What type of standard assumes no inefficiencies and perfect conditions?", o: ["Basic standard", "Ideal standard", "Current standard", "Normal standard"], c: "Ideal standard" },
            { q: "261. How often are standards usually revised?", o: ["Every month", "Annually", "Only when actual costs change", "At regular intervals based on changing conditions"], c: "At regular intervals based on changing conditions" },
            { q: "262. What is the effect of an adverse material usage variance?", o: ["Increased material cost", "Reduced material usage", "Lower labor cost", "Higher fixed overhead"], c: "Increased material cost" },
            { q: "263. A company budgets sales at 10,000 units at \u20b920 per unit. Variable cost is \u20b912/unit and fixed costs are \u20b940,000. What is the budgeted profit?", o: ["\u20b920,000", "\u20b930,000", "\u20b940,000", "\u20b980,000"], c: "\u20b940,000" },
            { q: "264. In a flexible budget, fixed costs are \u20b930,000. At 5,000 units, total variable cost is \u20b950,000. What is total cost at 6,000 units?", o: ["\u20b982,000", "\u20b990,000", "\u20b975,000", "\u20b998,000"], c: "\u20b990,000" },
            { q: "265. Budgeted production is 1,200 units. Opening stock 100, Closing stock 300. What is the sales budget?", o: ["1000 units.", "1200 units", "1300 units", "1600 units"], c: "1000 units." },
            { q: "266. Sales forecast for Jan to March: \u20b960,000, \u20b980,000, \u20b91,00,000, 30% sales are cash; 70% are credit, collected in next month. What are total receipts in March?", o: ["\u20b992,000", "30,000", "1,00,000", "86,000"], c: "86,000" },
            { q: "267. Sales forecast is \u20b95,00,000. Desired closing stock is 20% of next month's sales, and opening stock is \u20b940,000. If next month's sales are \u20b96,00,000, what is the required production (in \u20b9)?", o: ["\u20b95,80,000", "\u20b95,60,000", "\u20b94,20,000", "\u20b96,20,000"], c: "\u20b95,80,000" },
            { q: "268. Which of the following budgets is a \"summary budget\" of all departmental budgets?", o: ["Cash budget", "Master budget", "Flexible budget", "Functional budget"], c: "Master budget" },
            { q: "269. A flexible budget is preferable to a fixed budget because it", o: ["assumes a constant cost structure", "allows budget comparisons at various levels of activity", "cannot be adjusted once prepared", "ignores fixed costs"], c: "allows budget comparisons at various levels of activity" },
            { q: "270. Which type of budgeting starts from zero each period rather than adjusting prior budgets?", o: ["Incremental budgeting", "Zero-based budgeting", "Flexible budgeting", "Rolling budgeting"], c: "Zero-based budgeting" }
        ]
    },
    {
        setName: "Set 19",
        questions: [
            { q: "271. Rolling budgets are characterized by", o: ["being prepared only once a year", "having no fixed time horizon", "always shifting the budget horizon forward", "being rigid and not adaptable"], c: "always shifting the budget horizon forward" },
            { q: "272. A performance budget emphasises", o: ["classification by functions only", "cost centres only", "linkage between inputs and programme goals", "fixed cost control only"], c: "linkage between inputs and programme goals" },
            { q: "273. Which of the following is not a functional budget?", o: ["Sales budget", "Production budget", "Purchase budget", "Master budget"], c: "Master budget" },
            { q: "274. Benchmarking in budgetary control refers to", o: ["setting budgets using past years only", "comparing performance with best-in-class", "ignoring variances below a threshold", "inter-departmental negotiation"], c: "comparing performance with best-in-class" },
            { q: "275. Which cost remains constant per unit in flexible budgets?", o: ["Variable cost", "Fixed cost per unit", "Total fixed cost", "Semi-variable cost"], c: "Variable cost" },
            { q: "276. Which is not properly matched?", o: ["Cash budget-inflows/outflows", "Capital budget-fixed asset plans", "Master budget-overall plan", "Flexible budget-fixed for all activity"], c: "Flexible budget-fixed for all activity" },
            { q: "277. In zero-based budgeting, units must", o: ["accept previous budgets", "justify all expenditure", "prepare only supplements", "ignore activity levels"], c: "justify all expenditure" },
            { q: "278. Forecasting is different from budgeting in that", o: ["forecasting is binding, while budgeting is not", "budgeting is essentially prediction, while forecasting is commitment", "forecasting is estimation of future trends, budgeting is a plan/commitment based on that estimate", "forecasting is short term and budgeting is always long term"], c: "forecasting is estimation of future trends, budgeting is a plan/commitment based on that estimate" },
            { q: "279. Return on Investment (ROI) as a divisional performance measure is calculated as:", o: ["Net profit/Total assets", "Operating profit/Average operating assets", "Sales/Operating expenses", "Operating profit/Sales"], c: "Operating profit/Average operating assets" },
            { q: "280. Which of the following is the primary objective of divisional performance measurement?", o: ["Centralized decision-making", "Evaluate profitability and efficiency of divisions", "Increase company-wide bureaucrасу", "Eliminate responsibility centers"], c: "Evaluate profitability and efficiency of divisions" },
            { q: "281. Residual Income (RI) differs from ROI in that RI:", o: ["Measures absolute profit after deducting a charge for capital cost", "Ignores capital cost", "Is a ratio like ROI", "Always results in negative values"], c: "Measures absolute profit after deducting a charge for capital cost" },
            { q: "282. Economic Value Added (EVA) is best described as:", o: ["Net operating profit after tax minus cost of capital employed", "Operating profit divided by sales", "Net profit before tax minus fixed cost", "Total revenue minus total expenses"], c: "Net operating profit after tax minus cost of capital employed" },
            { q: "283. The DuPont analysis breaks down ROI into:", o: ["Profit margin and asset turnover", "Profit margin and sales growth", "Asset turnover and working capital", "Net income and equity"], c: "Profit margin and asset turnover" },
            { q: "284. Division A has operating profit \u20b920 lakhs and average operating assets \u20b91 crore. Division B has operating profit \u20b915 lakhs and average operating assets \u20b975 lakhs. Which division has a higher ROI?", o: ["Division A: 20%, Division B: 20%", "Division A: 25%, Division B: 20%", "Division A: 20%, Division B: 25%", "Division A: 15%, Division B: 18%"], c: "Division A: 20%, Division B: 20%" },
            { q: "285. Division X has operating profit of \u20b930 lakhs and operating assets of \u20b91.5 crore. Cost of capital is 15%. Calculate Residual Income (RI).", o: ["\u20b99.5 lakhs", "\u20b94.5 lakhs", "\u20b97.5 lakhs", "\u20b910 lakhs"], c: "\u20b97.5 lakhs" }
        ]
    },
    {
        setName: "Set 20",
        questions: [
            { q: "286. Division C's sales are \u20b950 lakhs; net operating profit \u20b98 lakhs; average operating assets \u20b940 lakhs. Calculate ROI.", o: ["\u20b910%", "20%", "14%", "18%"], c: "20%" },
            { q: "287. Division D's net operating profit after tax (NOPAT) is \u20b912 lakhs. Capital charge @ 18% on \u20b950 lakhs capital employed. Calculate Economic Value Added (EVA).", o: ["\u20b99 lakhs", "\u20b96 lakhs", "\u20b94.5 lakhs", "\u20b93 lakhs"], c: "\u20b93 lakhs" },
            { q: "288. Division Q's ROI is 18%. Cost of capital is 12%. Should Division Q accept a project with an ROI of 14%?", o: ["Yes, because project ROI > cost of capital", "No, because project ROI < divisional ROI", "Yes, if project is short term", "No, because project ROI < 20%"], c: "Yes, because project ROI > cost of capital" },
            { q: "289. Which of the following is NOT a responsibility center?", o: ["Cost center", "Profit center", "Investment center", "Tax center"], c: "Tax center" },
            { q: "290. Which of the following is NOT true about responsibility accounting?", o: ["Encourages accountability", "Helps in performance evaluation", "Eliminates all cost variances", "Facilitates decentralization"], c: "Eliminates all cost variances" },
            { q: "291. In responsibility accounting, controllable costs are:", o: ["Costs over which a manager has direct influence", "Fixed costs only", "Sunk costs", "Costs that cannot be controlled"], c: "Costs over which a manager has direct influence" },
            { q: "292. Profit center managers are responsible for:", o: ["Costs only", "Revenues only", "Both revenues and costs", "Investment decisions"], c: "Both revenues and costs" },
            { q: "293. Which responsibility center allows managers to make decisions on assets employed as well as profits?", o: ["Cost center", "Profit center", "Investment center", "Expense center"], c: "Investment center" },
            { q: "294. Which decision-making criterion assumes the decision maker is extremely risk-averse?", o: ["Maximax", "Maximin", "Minimax regret", "Expected value"], c: "Maximin" },
            { q: "295. The maximax criterion is also known as:", o: ["Optimistic criterion", "Pessimistic criterion", "Minimax regret", "Laplace criterion"], c: "Optimistic criterion" },
            { q: "296. The minimax regret criterion minimizes:", o: ["The maximum payoff", "The maximum loss relative to the best payoff in each state", "The expected value", "The minimum loss"], c: "The maximum loss relative to the best payoff in each state" },
            { q: "297. Expected monetary value (EMV) is calculated by:", o: ["Multiplying the payoff by the probability and summing for all states", "Taking the maximum payoff", "Subtracting costs from revenues", "Dividing total payoff by the number of alternatives"], c: "Multiplying the payoff by the probability and summing for all states" },
            { q: "298. Which of the following decision rules is suitable when probabilities of states of nature are unknown and the decision maker is neutral?", o: ["Maximin", "Maximax", "Laplace (Equal probability)", "Minimax regret"], c: "Laplace (Equal probability)" },
            { q: "299. In decision theory, a 'payoff table' shows:", o: ["Probabilities of states of nature", "Outcomes for each alternative under each state of nature", "Only the best outcome", "Budgeted costs and revenues"], c: "Outcomes for each alternative under each state of nature" },
            { q: "300. The Laplace criterion assumes:", o: ["Decision maker is pessimistic", "Decision maker assigns equal probabilities to all states of nature", "Probabilities are known precisely", "Focus only on worst outcomes"], c: "Decision maker assigns equal probabilities to all states of nature" }
        ]
    },
    {
        setName: "Set 21",
        questions: [
            { q: "301. A decision tree is useful because it:", o: ["Simplifies complex decisions by structuring alternatives and outcomes sequentially", "Ignores probabilities", "Always leads to optimistic decisions", "Is used only for investment decisions"], c: "Simplifies complex decisions by structuring alternatives and outcomes sequentially" },
            { q: "302. Sensitivity analysis in decision theory helps to:", o: ["Evaluate how changes in probabilities or payoffs affect the decision", "Eliminate bad alternatives", "Predict exact future outcomes", "Decide the cost of alternatives"], c: "Evaluate how changes in probabilities or payoffs affect the decision" },
            { q: "303. The 'Expected Value of Perfect Information (EVPI)' represents:", o: ["The cost of obtaining perfect information", "The maximum amount a decision maker would pay to eliminate uncertainty", "The average payoff", "The minimum payoff"], c: "The maximum amount a decision maker would pay to eliminate uncertainty" }
        ]
    }
];