// --- DATA: Term-wise MCQ Sets from CMA Financial Accounting (2017-2025) ---
const quizSets = [
    {
        setName: "June 2017",
        questions: [
            { q: "1. Creditors ledger adjustment account is opened in", o: ["(A) General Ledger", "(B) Debtors Ledger", "(C) Creditors Ledger", "(D) Either (B) or (C)"], c: "(A) General Ledger" },
            { q: "2. Receipts and Payments account is a", o: ["(A) Nominal Account", "(B) Real Account", "(C) Personal Account", "(D) Artificial Personal Account"], c: "(B) Real Account" },
            { q: "3. A resource owned by the business with purpose of using it for generating future profit, is known as", o: ["(A) Capital", "(B) Asset", "(C) Liability", "(D) Surplus"], c: "(B) Asset" },
            { q: "4. Outward Invoice issued is a source document of", o: ["(A) Purchase Book", "(B) Sales Book", "(C) Return Inward Book", "(D) Return Outward Book"], c: "(B) Sales Book" },
            { q: "5. Which of the following is of capital nature?", o: ["(A) Commission on purchases", "(B) Cost of repairs", "(C) Rent of factory", "(D) Wages paid for installation of machinery"], c: "(D) Wages paid for installation of machinery" },
            { q: "6. If any stock is taken by a co-venturer, it will be treated as", o: ["(A) an income of the joint venture", "(B) an expense of the joint venture", "(C) to be ignored from joint venture", "(D) it will be treated in the personal books of the co-venturer"], c: "(A) an income of the joint venture" },
            { q: "7. Contingent liability would appear", o: ["(A) on the liability side of the Balance Sheet", "(B) on the assets side of the Balance Sheet", "(C) do not shown in the books of accounts", "(D) as a note in Balance Sheet"], c: "(D) as a note in Balance Sheet" },
            { q: "8. Income statement of a Charitable Institution is known as", o: ["(A) Statement of profit and loss", "(B) Receipts and Payments Account", "(C) Income and Expenditure Account", "(D) Profit and Loss Account"], c: "(C) Income and Expenditure Account" },
            { q: "9. Which of the following account is mainly prepared at the time of dissolution of the firm", o: ["(A) Revaluation A/c", "(B) Goodwill A/c", "(C) Realization A/c", "(D) Memorandum Revaluation A/c"], c: "(C) Realization A/c" },
            { q: "10. Advertisement expenses are apportioned among departments in the proportion of", o: ["(A) sales of each department", "(B) purchases of each department", "(C) no. of units sold by each department", "(D) cost of sales of each department"], c: "(A) sales of each department" }
        ]
    },
    {
        setName: "December 2017",
        questions: [
            { q: "1. If an employee of the business files a legal suit on business, it is considered in the books as a", o: ["(A) Legal Expense", "(B) Liability", "(C) Contingent Asset", "(D) Contingent Liability"], c: "(D) Contingent Liability" },
            { q: "2. At the end of the accounting year the capital expenditures are shown in the", o: ["(A) assets side of the Balance Sheet", "(B) liabilities side of the Balance Sheet", "(C) debit side of the Profit and Loss A/c", "(D) credit side of the Profit and Loss A/c"], c: "(A) assets side of the Balance Sheet" },
            { q: "3. Which of the following is not a method of charging depreciation?", o: ["(A) Sinking Fund Method", "(B) Sum of years Digit Method", "(C) Working hours Method", "(D) Asset's Life-cycle Method"], c: "(D) Asset's Life-cycle Method" },
            { q: "4. If average inventory is ₹1,25,000 and closing inventory is ₹10,000 less than opening inventory then the value of closing inventory will be", o: ["(A) ₹1,35,000", "(B) ₹1,15,000", "(C) ₹1,30,000", "(D) ₹1,20,000"], c: "(D) ₹1,20,000" },
            { q: "5. The Accommodation bill is drawn", o: ["(A) to finance actual purchase or sale of goods", "(B) to facilitate trade transmission", "(C) when both parties are in need of funds", "(D) None of the above"], c: "(C) when both parties are in need of funds" },
            { q: "6. Balance of X's account in creditors ledger is transferred to X's account in debtors ledger, in this case", o: ["(A) X's account in debtors ledger will be debited", "(B) X's account in creditors ledger will be debited", "(C) Suspense account will be debited", "(D) None of the above"], c: "(B) X's account in creditors ledger will be debited" },
            { q: "7. Ground rent or surface rent means", o: ["(A) Minimum rent", "(B) Maximum royalty payable", "(C) Minimum royalty payable", "(D) Fixed rent payable in addition to minimum rent"], c: "(D) Fixed rent payable in addition to minimum rent" },
            { q: "8. Accounting standard in India are issued by", o: ["(A) Government of India", "(B) Reserve Bank of India", "(C) The Institute of Chartered Accountants of India", "(D) The Institute of Accounting Standard of India"], c: "(C) The Institute of Chartered Accountants of India" },
            { q: "9. As on 31st March, 2017 debtors; and additional bad debts are ₹8,00,000 and ₹10,000 respectively. If the provision for bad debts is made at 5% on debtors then amount of such provision will be", o: ["(A) ₹40,000", "(B) ₹50,000", "(C) ₹39,500", "(D) ₹40,500"], c: "(C) ₹39,500" },
            { q: "10. Income and Expenditure Account is a", o: ["(A) Nominal Account", "(B) Real Account", "(C) Personal Account", "(D) Artificial Personal Account"], c: "(A) Nominal Account" }
        ]
    },
    {
        setName: "June 2018",
        questions: [
            { q: "1. Which of the following is not a Qualitative Characteristics of Financial Statement?", o: ["(A) Cost Principle", "(B) Understandability", "(C) Relevance", "(D) Reliability"], c: "(A) Cost Principle" },
            { q: "2. Name the book in which, entries are recorded on the basis of credit notes issued.", o: ["(A) Sales Book", "(B) Purchase Book", "(C) Sales Return Book", "(D) Purchase Return Book"], c: "(C) Sales Return Book" },
            { q: "3. Exception to consistency principle is", o: ["(A) Cost Principle", "(B) Going Concern Principle", "(C) Matching Principle", "(D) Prudence Principle"], c: "(D) Prudence Principle" },
            { q: "4. Interest charged by vendor in Hire Purchase System, is calculated on the basis of", o: ["(A) Outstanding hire purchase price", "(B) Outstanding cash price", "(C) Instalment amount", "(D) Cost price of the asset"], c: "(B) Outstanding cash price" },
            { q: "5. The balance in consignment account shows", o: ["(A) Amount receivable from consignee", "(B) Amount payable to consignee", "(C) Profit/loss on consignment", "(D) Closing stock with consignee"], c: "(C) Profit/loss on consignment" },
            { q: "6. Provision for bad debts is", o: ["(A) Real Account", "(B) Nominal account", "(C) Personal account", "(D) None of the above"], c: "(C) Personal account" },
            { q: "7. The business is treated as distinct and separate from its owners on the basis of the", o: ["(A) Going concern concept", "(B) Conservatism concept", "(C) Matching concept", "(D) Business entity concept"], c: "(D) Business entity concept" },
            { q: "8. Due to retrospective effect on revision of salary of employees, the arrears of salary relating to past years, payable in current year is", o: ["(A) Prior period item", "(B) Extraordinary item", "(C) Ordinary item requiring separate disclosure", "(D) Contingent item"], c: "(C) Ordinary item requiring separate disclosure" },
            { q: "9. Discount given in the Sales - Invoice itself is", o: ["(A) Cash discount", "(B) Trade discount", "(C) Rebate", "(D) Allowance"], c: "(B) Trade discount" },
            { q: "10. Canteen expenses are apportioned among departments in the proportion of", o: ["(A) Departmental floor space", "(B) Departmental direct wages", "(C) Departmental sales", "(D) Departmental No. of employees"], c: "(D) Departmental No. of employees" }
        ]
    },
    {
        setName: "December 2018",
        questions: [
            { q: "1. Both cash and credit transactions are recorded, on the basis of", o: ["(A) Accounting Period Concept", "(B) Going Concern Concept", "(C) Business Entity Concept", "(D) Accrual Concept"], c: "(D) Accrual Concept" },
            { q: "2. Which of the following book is both a journal and a ledger?", o: ["(A) Cash Book", "(B) Sales Day Book", "(C) Bills Receivable Book", "(D) Journal Proper"], c: "(A) Cash Book" },
            { q: "3. Interest received in advance account is a", o: ["(A) Nominal Account", "(B) Real Account", "(C) Artificial Personal Account", "(D) Representative Personal Account"], c: "(D) Representative Personal Account" },
            { q: "4. Shiva draws a bill on Sanat on 25th October, 2018 for 90 days, the maturity date of the bill will be", o: ["(A) 27th January, 2019", "(B) 26th January, 2019", "(C) 25th January, 2019", "(D) 28th January, 2019"], c: "(C) 25th January, 2019" },
            { q: "5. Peeru and Simu are entered in the business of buy and sale of food grain for a period of one year and sharing the profit in the ratio of 3: 2, this agreement is a", o: ["(A) Partnership", "(B) Consignment", "(C) Joint-venture", "(D) Lease"], c: "(C) Joint-venture" },
            { q: "6. At the end of the year 2017-18, Prepaid Insurance Premium ₹7,500 appeared in the Trial Balance, it will be shown", o: ["(A) only in Profit & Loss Account", "(B) only in Balance Sheet", "(C) both in Profit & Loss Account and in Balance Sheet", "(D) not in Both in Profit & Loss Account and in Balance Sheet"], c: "(B) only in Balance Sheet" },
            { q: "7. Contingent Liability would appear", o: ["(A) on the liabilities side of the Balance Sheet", "(B) on the assets side of the Balance Sheet", "(C) as a note in the Balance Sheet", "(D) None of the above"], c: "(C) as a note in the Balance Sheet" },
            { q: "8. Debtors Ledger Adjustment Account is opened in the", o: ["(A) Debtors Ledger", "(B) Creditors Ledger", "(C) General Ledger", "(D) Both Creditors Ledger and General Ledger"], c: "(C) General Ledger" },
            { q: "9. Generally sacrifice ratio is concerned with the situation of", o: ["(A) Admission of a new partner", "(B) Retirement of a partner", "(C) Dissolution of firm", "(D) Conversion of firm into company"], c: "(A) Admission of a new partner" },
            { q: "10. KCS purchased a machine from JPS on hire purchase system, whose cash price was 8,64,000. ₹2,16,000 being paid on delivery and balance in three annual instalments of 2,88,000 each. The amount of interest included in first installment would be", o: ["(A) ₹72,000", "(B) ₹57,600", "(C) ₹1,08,000", "(D) ₹36,000"], c: "(C) ₹1,08,000" }
        ]
    },
    {
        setName: "June 2019",
        questions: [
            { q: "1. Which of the following is a resource owned by the business with the purpose of using it for generating future profits?", o: ["(A) Loan from Bank", "(B) Owner's Capital", "(C) Trade Mark", "(D) All of the above"], c: "(C) Trade Mark" },
            { q: "2. Chandu & Co.'s Account is a", o: ["(A) Real Account", "(B) Nominal Account", "(C) Representative Personal Account", "(D) Artificial Personal Accounts"], c: "(D) Artificial Personal Accounts" },
            { q: "3. Purchase of a laptop for office use wrongly debited to Purchase Account. It is an error of", o: ["(A) Omission", "(B) Commission", "(C) Principle", "(D) Misposting"], c: "(C) Principle" },
            { q: "4. Which of the following term is most suitable for writing off Patent?", o: ["(A) Depletion", "(B) Amortization", "(C) Depreciation", "(D) All of the above"], c: "(B) Amortization" },
            { q: "5. Memorandum Joint Venture Account is prepared when", o: ["(A) the separate set of books is maintained for Joint Venture", "(B) the each Co-venturer keeps records of all transactions", "(C) the each Co-venturer keeps records of their own transactions only", "(D) All of the above cases"], c: "(C) the each Co-venturer keeps records of their own transactions only" },
            { q: "6. Which of the following commission is allowed by the consignor to the consignee to encourage the consignee for putting-up hard work in introducing new product in the market?", o: ["(A) Del-credere Commission", "(B) Over-riding Commission", "(C) Hard work Commission", "(D) Ordinary Commission"], c: "(B) Over-riding Commission" },
            { q: "7. If Ram's acceptance which was endorsed by us in favour of Saleem is dishonoured, then the amount will be debited in our books to", o: ["(A) Saleem", "(B) Ram", "(C) Bills Receivable Account", "(D) None of the above"], c: "(B) Ram" },
            { q: "8. In case of a Club, the excess of expenditure over income is called as", o: ["(A) Surplus", "(B) Deficit", "(C) Capital Fund", "(D) Investment in Fixed Assets"], c: "(B) Deficit" },
            { q: "9. A Charitable Institution has 250 members with a annual subscription of ₹5,000 each. The subscription received during 2018-19 were ₹11,25,000, which include ₹65,000 and 25,000 for the years of 2017-18 and 2019-20 respectively. Amount of outstanding subscription for the 2018-19 will be", o: ["(A) ₹90,000", "(B) ₹1,25,000", "(C) ₹2,15,000", "(D) 1,90,000"], c: "(C) ₹2,15,000" },
            { q: "10. Items - Historical Cost (Lakh) / Net Realisable Value (Lakh): A: 30/27, B: 15/18, C: 35/35, D: 40/45 The value of Closing Stock will be", o: ["(A) 120 Lakh", "(B) 125 Lakh", "(C) 117 Lakh", "(D) 128 Lakh"], c: "(C) 117 Lakh" }
        ]
    },
    {
        setName: "December 2019",
        questions: [
            { q: "1. When stock is valued at cost in one accounting period and at lower of cost and Net realizable value in another accounting period", o: ["(A) Prudence Principle conflicts with Consistency Principle", "(B) Matching Principle conflicts with Consistency principle", "(C) Consistency Principle conflicts with Accounting Period Assumption", "(D) None of the above"], c: "(A) Prudence Principle conflicts with Consistency Principle" },
            { q: "2. Materiality Principle is an exception to the", o: ["(A) Consistency principle", "(B) Full disclosure Principle", "(C) Accounting Period Assumption", "(D) Prudence Principle"], c: "(B) Full disclosure Principle" },
            { q: "3. In a Cash Book Debit balance of ₹112 brought forward as credit balance of 121, while preparing a Bank Reconciliation Statement taking the balance as per Cash Book as the starting point:", o: ["(A) ₹112 to be added", "(B) 121 to be added", "(C) 233 to be added", "(D) 112 to be subtracted"], c: "(C) 233 to be added" },
            { q: "4. ________ represents a potential obligation that could be created depending on the outcome of an event.", o: ["(A) Internal Liability", "(B) Current Liability", "(C) Contingent Liability", "(D) Non-current Liability"], c: "(C) Contingent Liability" },
            { q: "5. Opening Debtors, Collection from Debtors and Discount Allowed were 3,15,000; 18,30,000 and ₹35,000 respectively. If the closing debtors were 20% of credit sales of the period then closing debtors and credit sales would be", o: ["(A) ₹3,51,667 and 17,58,333", "(B) ₹3,63,333 and ₹18,16,667", "(C) ₹3,87,500 and ₹19,37,500", "(D) ₹3,10,000 and ₹15,50,000"], c: "(C) ₹3,87,500 and ₹19,37,500" },
            { q: "6. Opening Stock ₹2,13,000, Purchase 16,55,000, Sales ₹21,32,000, Carriage Inwards 32,500, Carriage Outwards 38,600, Return Inwards 38,000. If the rate of gross profit is 25% on cost then value of closing stock will be", o: ["(A) ₹2,57,800", "(B) ₹1,94,900", "(C) ₹2,25,300", "(D) ₹3,30,000"], c: "(C) ₹2,25,300" },
            { q: "7. Provision for Doubtful Debt on 1st April, 2018 was 21,500. During the year 2018-19 the Bad-debt and Recovery of Bad-debt were ₹10,500 and ₹2,100 respectively. The Sundry Debtors on 31st March, 2019 were ₹2,25,000. Provision is to be made @ 5% on Debtors. If on 31st March, 2019, there was additional Bad-debt of ₹2,500 then Provision for doubtful-debt will be", o: ["(A) debited to Profit & Loss Account by 11,250", "(B) debited to Profit & Loss Account by ₹2,625", "(C) debited to Profit & Loss Account by ₹3,000", "(D) debited to Profit & Loss Account by ₹900"], c: "(B) debited to Profit & Loss Account by ₹2,625" },
            { q: "8. A and B enter into a joint venture sharing profit and losses in the ratio of 3:2. A purchased goods costing ₹2,00,000. B sold 95% goods for 2,50,000. A is entitled to get 1% commission on purchase and B is entitled to get 5% commission on sales. A drew a bill on B for an amount equivalent to 80% of original cost of goods. A got it discounted at 1,50,000. What is A's share of profit?", o: ["(A) ₹15,300", "(B) ₹21,300", "(C) 18,900", "(D) None of the above"], c: "(B) ₹21,300" },
            { q: "9. Subscription of ₹6,25,000 had been shown in the Income and Expenditure Account prepared for the year ending 31st March, 2019. Subscription Outstanding: 31-Mar-2018: 55,000, 31-Mar-2019: ₹72,000. Subscription Received in Advance: 31-Mar-2018: 31,000, 31-Mar-2019: ₹37,000. The amount of subscription received during the year 2018-19 would be", o: ["(A) ₹6,36,000", "(B) ₹6,02,000", "(C) ₹6,14,000", "(D) ₹6,48,000"], c: "(C) ₹6,14,000" },
            { q: "10. X and Y are partners with the capital of ₹50,000 and ₹30,000 respectively. Interest Payable on Capital is 10% p.a. If the profits earned by the firm is ₹4,800, what will be the Interest on Capital for X and Y?", o: ["(A) ₹5,000 and ₹3,000", "(B) ₹3,000 and ₹1,800", "(C) No interest will be paid to the partners", "(D) None of the above"], c: "(B) ₹3,000 and ₹1,800" }
        ]
    },
    {
        setName: "December 2021",
        questions: [
            { q: "1. In hire purchase System, cash price plus interest is known as", o: ["1. Hire purchase charges", "2. Capital value of asset", "3. Hire purchase price of assets", "4. Book value of asset"], c: "3. Hire purchase price of assets" },
            { q: "2. Depreciation is calculated from the date of ________.", o: ["1. Assets put to use", "2. Purchase of assets", "3. Assets installed", "4. Receipts of assets at business premises"], c: "1. Assets put to use" },
            { q: "3. Debit balance in the cash book is equivalent to ________.", o: ["1. Overdraft as per cash book", "2. None of these", "3. Credit balance as per Passbook", "4. Overdraft as per passbook"], c: "4. Overdraft as per passbook" },
            { q: "4. Main elements of the accounting equation are:", o: ["1. Cash, stock and debtors", "2. Bank balance, Investments and bills receivable", "3. Assets, liabilities and capital", "4. Capital, creditors and bills payable"], c: "3. Assets, liabilities and capital" },
            { q: "5. A Bill of Exchange cannot be", o: ["1. Endorsed", "2. Crossed", "3. None of these", "4. Accepted"], c: "3. None of these" },
            { q: "6. Spent amount on unsuccessful promotion policy is", o: ["1. Capital expenditure", "2. Expenses", "3. Revenue expenditure", "4. Deferred revenue expenditure"], c: "3. Revenue expenditure" },
            { q: "7. Convention of Conservatism takes into account:", o: ["1. All future profits and not losses", "2. Neither profits nor losses of the future", "3. All future losses and not profits", "4. All future profits and losses"], c: "3. All future losses and not profits" },
            { q: "8. Balance Sheet is prepared with the balances of which of the following?", o: ["1. All balances in the Ledger", "2. Balances of real accounts", "3. Balances of personal accounts", "4. Balances of personal and real accounts"], c: "4. Balances of personal and real accounts" },
            { q: "9. Which of these terms/concepts are not relevant to a joint venture?", o: ["1. Co venturers", "2. Temporary partnership", "3. Principal and agent relationship", "4. Sharing profit and loss of joint ventures"], c: "3. Principal and agent relationship" },
            { q: "10. Excess of minimum rent over royalty payable is known as", o: ["1. Minimum royalty payable", "2. Deficiency of actual royalty", "3. Excess working", "4. Short working"], c: "4. Short working" },
            { q: "11. Sold goods worth list price of ₹8000 at 10% trade discount and 2% cash discount. 25% received at the time of transaction only. The amount posted to the discount account will be:", o: ["1. ₹144 on credit side", "2. 36 on debit side", "3. 144 on debit side", "4. ₹40 on credit side"], c: "3. 144 on debit side" },
            { q: "12. Revenue from ________ is recognised as per AS-9", o: ["1. Construction contract", "2. Lease agreement", "3. Insurance contract", "4. Rendering the services"], c: "4. Rendering the services" },
            { q: "13. Bills payable honoured during the year, will be debited to ________.", o: ["1. None of these", "2. Creditors account", "3. Bills payable account", "4. Cash account"], c: "2. Creditors account" },
            { q: "14. Which of the following is not an essential feature of a partnership firm?", o: ["1. Mutual agency", "2. Existence of business", "3. Association of two or more people", "4. Compulsory registration"], c: "4. Compulsory registration" },
            { q: "15. Sacrificing ratio is ________.", o: ["1. New Profit sharing ratio - old profit sharing ratio", "2. Equal to old profit sharing ratio", "3. Equal", "4. Old profit sharing ratio - new profit sharing ratio"], c: "4. Old profit sharing ratio - new profit sharing ratio" },
            { q: "16. Which of the following statements is not correct?", o: ["1. Bad debts can be less than the amount of provision for doubtful debts", "2. Bad debts can be more than the amount of provision for doubtful debts", "3. Provision for doubtful debts account is the amount payable to debtors", "4. Provision for doubtful debts is shown in the balance sheet"], c: "3. Provision for doubtful debts account is the amount payable to debtors" },
            { q: "17. Errors are:", o: ["1. Frauds", "2. Undetected mistake", "3. Intentional mistake", "4. Unintentional mistake"], c: "4. Unintentional mistake" },
            { q: "18. Choose the correct statement.", o: ["1. Financial statements need not take into consideration any statutory requirement", "2. Only credit transactions are recorded in books of accounts", "3. Financial statements prepared by two different accountants will always show identical results", "4. Financial accounts, of an enterprise, are treated as evidence in the Court of Law"], c: "4. Financial accounts, of an enterprise, are treated as evidence in the Court of Law" },
            { q: "19. Which of the following are not the advantages of pre packaged accounting software?", o: ["1. Report generated", "2. Simple backup procedure", "3. Easy to use", "4. Easy to install"], c: "1. Report generated" },
            { q: "20. Which of these is/are one of the methods of stock taking?", o: ["1. Periodic inventory", "2. Perpetual inventory", "3. Both", "4. None"], c: "3. Both" }
        ]
    },
    {
        setName: "June 2022",
        questions: [
            { q: "1. Select the correct statement:", o: ["(A) Keeping systematic recording of business transaction is not the function of Financial Accounting", "(B) Accounting is concerned with monetary transactions", "(C) Accounting is concerned with past as well as future events", "(D) Business and Businessmen are the same identity from accounting point of view"], c: "(B) Accounting is concerned with monetary transactions" },
            { q: "2. Going concern concept is not followed", o: ["(A) by Bank", "(B) by Cooperative Societies", "(C) Joint Venture Accounting", "(D) Depreciation Accounting"], c: "(C) Joint Venture Accounting" },
            { q: "3. Rectification of which type of errors requires opening of Suspense Account", o: ["(A) Errors of Principle", "(B) Complete Omission", "(C) Partial Omission", "(D) Errors of Commission"], c: "(C) Partial Omission" },
            { q: "4. A buyer returning goods on the ground of poor quality sent a note along with the goods stating that no payment would be made in respect of goods returned, the return note is called", o: ["(A) Debit note", "(B) Credit note", "(C) Refund note", "(D) Return note"], c: "(A) Debit note" },
            { q: "5. Which of these expenses is/are not included in valuation of abnormal loss?", o: ["(A) Godown Rent", "(B) Freight and Insurance incurred by Consignor", "(C) Transit Insurance incurred by Consignee", "(D) Loading and Unloading expenses incurred by Consignor"], c: "(A) Godown Rent" },
            { q: "6. Goods sold by other co-venturer is debited to", o: ["(A) Joint Venture Account", "(B) Other Co-venturer's Personal Account", "(C) Joint Bank Account", "(D) None of the above"], c: "(B) Other Co-venturer's Personal Account" },
            { q: "7. Sale is recognised as revenue", o: ["(A) when the contract for sale is entered into", "(B) at the point of sale or performance of service", "(C) after the expiry of credit period allowed to Debtors", "(D) after the money collected from the customers"], c: "(B) at the point of sale or performance of service" },
            { q: "8. Case: A and B are partners sharing profits and losses in the ratio of 3:2. They admitted C with effect from 1st April, 2021. New profit sharing ratio is agreed at 4:3:3. Workmen Compensation Reserve ₹90,000. If there is no other information in respect of Workmen Compensation Reserve:", o: ["(A) Cr. A's Capital A/c with ₹60,000 and B's Capital A/c with ₹30,000", "(B) Cr. A's Capital A/c with 54,000 and B's Capital A/c with ₹36,000", "(C) Dr. A's Capital A/c with ₹54,000 and B's Capital A/c with ₹36,000", "(D) Cr. A's Capital A/c with ₹36,000 and B's Capital A/c with 27,000 and C's Capital A/c with 27,000"], c: "(B) Cr. A's Capital A/c with 54,000 and B's Capital A/c with ₹36,000" },
            { q: "9. Case (continued): If a claim for Workmen Compensation is estimated at ₹60,000:", o: ["(A) Cr. A's Capital A/c with 20,000 and B's Capital A/c with ₹10,000", "(B) Dr. A's Capital A/c with 18,000 and B's Capital A/c with ₹12,000", "(C) Cr. A's Capital A/c with ₹18,000 and B's Capital A/c with 12,000", "(D) Cr. A's Capital A/c with 12,000 and B's Capital A/c with ₹9,000 and C's Capital A/c with ₹9,000"], c: "(C) Cr. A's Capital A/c with ₹18,000 and B's Capital A/c with 12,000" },
            { q: "10. Case (continued): If a claim for Workmen Compensation is estimated at 1,50,000:", o: ["(A) Dr. C's Capital with ₹60,000", "(B) Dr. C's Capital A/c with ₹18,000", "(C) Dr. Workmen Compensation Reserve A/c with ₹90,000 and Revaluation A/c with ₹60,000", "(D) Dr. Revaluation A/c with ₹60,000"], c: "(C) Dr. Workmen Compensation Reserve A/c with ₹90,000 and Revaluation A/c with ₹60,000" }
        ]
    },
    {
        setName: "June 2023",
        questions: [
            { q: "1. Which of the following is not a qualitative characteristics of accounting information?", o: ["(A) Reliability", "(B) Materiality", "(C) Comparability", "(D) Understandability"], c: "(B) Materiality" },
            { q: "2. IND-AS are", o: ["(A) rule based accounting standard", "(B) principle based accounting standard", "(C) partially rule based and partially principle based accounting standard", "(D) None of the above"], c: "(B) principle based accounting standard" },
            { q: "3. An increase in which of the following Account will be recorded on the debit side?", o: ["(A) Rent Received Account", "(B) Building Account", "(C) Bills Payable Account", "(D) Capital Account"], c: "(B) Building Account" },
            { q: "4. Trade Discount allowed is deducted from the gross sales. Sale is recorded in the Books of Account at", o: ["(A) gross sales and trade discount separately", "(B) net sales invoice", "(C) None of the above", "(D) Any of (A) or (B)"], c: "(D) Any of (A) or (B)" },
            { q: "5. Rebate is calculated for the period between date of", o: ["(A) payment and maturity date", "(B) drawing and payment of bill", "(C) drawing and maturity date", "(D) None of the above"], c: "(C) drawing and maturity date" },
            { q: "6. Which of the following is not an error of Principle?", o: ["(A) purchase of machinery debited to purchase Account", "(B) sale of old furniture credited to Sales Account", "(C) repairs on the overhauling of existing machinery debited to Machinery Account", "(D) cash received from Rana posted to Jana"], c: "(D) cash received from Rana posted to Jana" },
            { q: "7. Income tax paid by a sole trader is shown", o: ["(A) on the debit side of the Trading Account", "(B) on the debit side of Profit & Loss Account", "(C) as deduction from Capital in the Balance Sheet", "(D) as addition to Capital in the Balance Sheet"], c: "(C) as deduction from Capital in the Balance Sheet" },
            { q: "8. A lease which is generally not cancealable and cover full economic life of the asset is known as", o: ["(A) Sale and lease back", "(B) Operating lease", "(C) Finance lease", "(D) Economic lease"], c: "(C) Finance lease" },
            { q: "9. A charitable Institution has 250 members with an annual subscription of ₹5,000 each. The subscription received during 2020-21 were ₹11,25,000, which include ₹65,000 and ₹25,000 for the year 2019-20 and 2021-22 respectively. Amount of outstanding subscription for the year 2020-21 will be", o: ["(A) ₹90,000", "(B) ₹1,25,000", "(C) ₹2,15,000", "(D) ₹1,90,000"], c: "(C) ₹2,15,000" },
            { q: "10. X and Y are partners with a capital of ₹50,000 and ₹30,000 respectively. Interest payable on capital is 10% per annum. If the profits earned by the firm is 4,800, what will be the interest on capital for X and Y?", o: ["(A) ₹5,000, ₹3,000", "(B) ₹3,000, ₹1,800", "(C) No interest will be paid to the partners", "(D) None of the above"], c: "(B) ₹3,000, ₹1,800" },
            { q: "11. Which class of account is Consignment Account?", o: ["(A) Personal Account", "(B) Real Account", "(C) Representative Personal Account", "(D) Nominal Account"], c: "(D) Nominal Account" },
            { q: "12. Memorandum Joint Venture Account is prepared when", o: ["(A) the seperate set of books is maintained for Joint Venture", "(B) the each co-venturer keeps records of all transactions", "(C) the each co-venturer keeps records of their own transaction only", "(D) All of the above cases"], c: "(C) the each co-venturer keeps records of their own transaction only" }
        ]
    },
    {
        setName: "December 2023 (Paper 6)",
        questions: [
            { q: "1. The construction of a factory building was completed on 1st April, 2023, at a cost of 56,50,000. A sum of ₹45,000 had been incurred for the construction of the temporary huts for storing building materials. Insurance premium of ₹56,500 paid on 5th April, 2023. The capital and revenue expenditure would be", o: ["(A) Capital Expenditure 57,51,500 and Revenue Expenditure nil", "(B) Capital Expenditure ₹56,95,000 and Revenue Expenditure ₹56,500", "(C) Capital Expenditure ₹56,50,000 and Revenue Expenditure ₹1,01,500", "(D) Capital Expenditure ₹57,23,250 and Revenue Expenditure ₹28,250"], c: "(B) Capital Expenditure ₹56,95,000 and Revenue Expenditure ₹56,500" },
            { q: "2. If a receipt of ₹21,500 for interest has been recorded in the books as payment of 12,500 for interest, the profits would show-", o: ["(A) an increase of ₹9,000", "(B) an increase of ₹34,000", "(C) a decrease of ₹9,000", "(D) a decrease of ₹34,000"], c: "(D) a decrease of ₹34,000" },
            { q: "3. Shiva received a bill for ₹58,550 from Vijay and endorsed it in favour of Makkhu. On the date of maturity, the bill was dishonoured and for it noting charges of ₹450 paid by holder. In this case Shiva will debit", o: ["(A) Vijay by ₹58,550", "(B) Vijay by ₹58,100", "(C) Vijay by ₹59,000", "(D) Noting charges account by ₹450"], c: "(C) Vijay by ₹59,000" },
            { q: "4. Joint Venture with XYZ Account, is opened", o: ["(A) when separate set of books is maintained for joint venture", "(B) when not maintaining separate set of books for joint venture but every Co-venturer keeps record his own transactions only", "(C) when not maintaining separate set of books for joint venture but every Co-venturer keeps complete record of all the transactions", "(D) In all the above situations, (A), (B) and (C)"], c: "(B) when not maintaining separate set of books for joint venture but every Co-venturer keeps record his own transactions only" },
            { q: "5. On 31st March, 2023, the debtors of a trader are ₹6,20,000 before writing off the bad debts of ₹15,000. The provision for bad and doubtful debts is 5% on debtors and provision for discount on debtors is 2%. The amount of provision for discount on debtors is", o: ["(A) ₹12,400", "(B) 12,100", "(C) 11,495", "(D) 11,780"], c: "(C) 11,495" },
            { q: "6. Salaries paid during the year 2022-23 were 4,70,000. Salaries outstanding on 01.04.2022 were ₹65,000 and it was also outstanding for three months on 31.03.2023. The amount of salaries shown in Income and Expenditure Account will be-", o: ["(A) ₹5,35,000", "(B) ₹4,00,000", "(C) ₹5,40,000", "(D) ₹4,05,000"], c: "(C) ₹5,40,000" },
            { q: "7. Profit before interest on loan and manager's commission were 4,25,250. Interest on loan is 42,000. If the manager is entitled a commission of 5% on net profit after charging such commission then manager's commission will be-", o: ["(A) ₹20,250", "(B) 21,262.50", "(C) 19,162.50", "(D) 18,250"], c: "(D) 18,250" },
            { q: "8. At the end of the accounting year, advances from customers are", o: ["(A) debited to Profit and Loss account", "(B) credited to Profit and Loss account", "(C) shown in the Balance Sheet as assets", "(D) shown in Balance Sheet as liabilities"], c: "(D) shown in Balance Sheet as liabilities" },
            { q: "9. On 31.03.2023 the debtors of a trader are ₹7,50,000 before writing off the bad debts of 25,000. The provision for bad and doubtful debts is 5% on debtors and provision for discount on debtors is 2%. The amount of net debtors shown in the balance sheet as at 31.03.2023, will be", o: ["(A) ₹6,74,250", "(B) ₹6,74,975", "(C) ₹6,98,250", "(D) ₹6,97,500"], c: "(B) ₹6,74,975" },
            { q: "10. Following information for year ending 31.03.2023: Salaries outstanding and paid in advance on 01.04.2022 were ₹33,000 and ₹22,000 respectively. Salaries paid during the year 2022-2023 ₹3,30,000. Salaries paid in advance and outstanding on 31.03.2023 were 16,500 and ₹44,000 respectively. The amount of salaries to be shown in Income and Expenditure Account for the year ending 31.03.2023, will be", o: ["(A) ₹3,46,500", "(B) ₹2,91,500", "(C) ₹3,13,500", "(D) ₹3,68,500"], c: "(A) ₹3,46,500" },
            { q: "11. Opening Stock, Closing Stock, Sales Return and Sales are ₹2,80,000; ₹3,20,000; ₹45,000 and 24,20,000 respectively. If rate of gross profit is 25% on cost, then gross profit will be-", o: ["(A) ₹6,05,000", "(B) ₹4,75,000", "(C) ₹4,84,000", "(D) ₹5,93,750"], c: "(B) ₹4,75,000" },
            { q: "12. Only items of revenue nature pertaining to the period of accounts are shown in the", o: ["(A) Receipts and Payments Account", "(B) Income and Expenditure Account", "(C) Both (A) and (B)", "(D) Balance Sheet"], c: "(B) Income and Expenditure Account" },
            { q: "13. Excess of Hire-purchase price over the cash price is known as", o: ["(A) Depreciation", "(B) Penalty", "(C) Interest", "(D) Instalment"], c: "(C) Interest" },
            { q: "14. AS-10 is applicable to which one of the following assets?", o: ["(A) Construction Contracts", "(B) Live stock", "(C) Plantation", "(D) Property, Plant and Equipment"], c: "(D) Property, Plant and Equipment" },
            { q: "15. Goods costing ₹2,34,000 are sent to the Branch at a invoice price of ₹3,12,000. The loading on Invoice price is", o: ["(A) 20%", "(B) 25%", "(C) 33.33%", "(D) 28%"], c: "(B) 25%" }
        ]
    },
    {
        setName: "December 2023 (Paper 5)",
        questions: [
            { q: "1. represents a potential obligation that could be created depending on the outcome of an event.", o: ["(A) Internal Liability", "(B) Current Liability", "(C) Contingent Liability", "(D) Non-current Liability"], c: "(C) Contingent Liability" },
            { q: "2. On the basis of which of the following concept, a business is assumed to exist for an indefinite period and is not established with the objective of closing it down:", o: ["(A) Business Entity Concept", "(B) Going Concern Concept", "(C) The Accounting Period Concept", "(D) The Concept of Consistency"], c: "(B) Going Concern Concept" },
            { q: "3. Accounting events can be", o: ["(A) Internal", "(B) External", "(C) Either Internal or External", "(D) Neither Internal nor External"], c: "(C) Either Internal or External" },
            { q: "4. In a loss of profit policy, Net Profit, Insured Standing Charges, Uninsured Standing Charges and Rate of Gross Profit for the last financial year are ₹6,20,000; ₹2,60,000; 80,000; and 25% respectively. If the firm incurred additional expenses amounted to 85,000 which reduced the loss in turnover of ₹3,50,000, then admissible amount for claim of additional expenses will be", o: ["(A) ₹85,000", "(B) ₹77,917", "(C) 21,250", "(D) ₹87,500"], c: "(B) ₹77,917" },
            { q: "5. Provision for Doubtful Debt on 1st April, 2022 was 21,500. During the year 2022-23 the bad-debt and recovery of bad-debt were ₹10,500 and ₹2,100 respectively. The sundry debtors on 31st March, 2023 were ₹2,25,000. Provision is to be made @5% on debtors. If on 31st March, 2023, there was additional bad-debt of ₹2,500 then provision for doubtful-debt will be", o: ["(A) debited to Profit and Loss Account by 11,250", "(B) debited to Profit and Loss Account by ₹2,625", "(C) debited to Profit and Loss Account by ₹3,000", "(D) debited to Profit and Loss Account by ₹900"], c: "(B) debited to Profit and Loss Account by ₹2,625" },
            { q: "6. Opening Stock 2,13,000, Purchases 16,55,000, Sales 21,32,000, Carriage Inwards 32,500, Carriage Outwards 38,600, Return Inwards ₹38,000. If the rate of gross profit is 25% on cost then value of closing stock will be", o: ["(A) ₹2,57,800", "(B) ₹1,94,900", "(C) ₹3,30,000", "(D) ₹2,25,300"], c: "(D) ₹2,25,300" },
            { q: "7. Subscription of ₹6,25,000 had been shown in the Income and Expenditure Account prepared for the year ending 31st March, 2023. Subscription Outstanding (31-Mar-2022: 55,000, 31-Mar-2023: ₹72,000). Subscription Received in Advance (31-Mar-2022: 31,000, 31-Mar-2023: ₹37,000). The amount of subscription received during the year 2022-23 would be", o: ["(A) ₹6,14,000", "(B) ₹6,36,000", "(C) ₹6,02,000", "(D) ₹6,48,000"], c: "(A) ₹6,14,000" },
            { q: "8. Opening Debtors, Collection from Debtors and Discount Allowed were 3,15,000; 18,30,000; and ₹35,000 respectively. If the closing debtors were 20% of credit sales of the period then closing debtors and credit sales would be", o: ["(A) ₹3,51,667 & 17,58,333", "(B) ₹3,63,333 & 18,16,667", "(C) ₹3,87,500 & 19,37,500", "(D) ₹3,10,000 & ₹15,50,000"], c: "(C) ₹3,87,500 & 19,37,500" },
            { q: "9. A, B and C were partners in a firm. On B's date of retirement 31st July, 2022 his unsettled capital was 18,50,000. During the year ended 31st March, 2023, Net Profit carned by the firm after B's retirement was 2,08,125. If A's and C's Capitals were 21,00,000 and ₹16,00,000 respectively then according to Section 37 of the Indian Partnership Act, 1932, B is entitled to", o: ["(A) ₹1,07,917", "(B) ₹69,375", "(C) ₹46,250", "(D) ₹74,000"], c: "(D) ₹74,000" },
            { q: "10. Goods costing 68,000 were transferred from Department 'A' to Department 'B' at a profit of 25% on cost. Out of this, goods having transfer price of ₹25,000 were included in the closing stock of Department 'B'. The amount of provision for unrealised profit will be", o: ["(A) ₹6,250", "(B) ₹5,000", "(C) 17,000", "(D) None of the above"], c: "(B) ₹5,000" }
        ]
    },
    {
        setName: "June 2024",
        questions: [
            { q: "1. Select the correct equation:", o: ["(A) Owners Equity = Assets + Liabilities", "(B) Owners Equity + Outside Liabilities = Total Assets", "(C) Assets + Owner Equity = Outside Liabilities", "(D) Outside Equity + Profit = Total Assets"], c: "(B) Owners Equity + Outside Liabilities = Total Assets" },
            { q: "2. Cash In Hand A/c may have.", o: ["(A) Only debit balance", "(B) Only credit balance", "(C) Debt or Credit balance", "(D) All of the above"], c: "(A) Only debit balance" },
            { q: "3. Fundamental accounting assumptions are", o: ["(A) going concern, consistency and accrual", "(B) going concern, money measurement and prudence", "(C) going concern, business entity and accounting period", "(D) going concern, matching and consistency"], c: "(A) going concern, consistency and accrual" },
            { q: "4. Choose the correct statement:", o: ["(A) Errors of principle do not affect agreement of trial balance", "(B) Compensating errors affect trial balance", "(C) One side error does not affect trial balance", "(D) Error of casting is an error of principle"], c: "(A) Errors of principle do not affect agreement of trial balance" },
            { q: "5. Calculate sales from the following details: Opening Stock 4,000, Cost of Goods sold 30,000, Closing Stock 2,000, Direct Expenses ₹5,000, Gross Profit ₹1,500", o: ["(A) ₹28,000", "(B) ₹31,500", "(C) ₹32,000", "(D) ₹33,000"], c: "(B) ₹31,500" },
            { q: "6. Mr. P issued Cheques worth ₹15,000 in March, 2024, out of which ₹10,000 only were presented for payment by 31st March, 2024. While reconciling bank and cash book balance as on 31st March, 2024, how much would be added to balance as per Cash Book to arrive at balance as per Pass Book?", o: ["(A) 15,000", "(B) ₹10,000", "(C) ₹5,000", "(D) ₹7,500"], c: "(C) ₹5,000" },
            { q: "7. A second hand car purchased for ₹2,00,000 (excluding initial repair cost of ₹50,000) is sold for ₹1,00,000 after 2 years. If depreciation is charged at the rate 20% on WDV, profit or loss on sale of car is", o: ["(A) Profit ₹28,000", "(B) Profit ₹60,000", "(C) Loss ₹60,000", "(D) Loss ₹28,000"], c: "(C) Loss ₹60,000" },
            { q: "8. X drew a bill of exchange on Y for ₹20,000 payable after 3 months. On the due date, Y could not make the payment and requested to renew a fresh bill for another 3 months at 12% interest. The amount of fresh bill would be", o: ["(A) ₹20,600", "(B) ₹22,400", "(C) 21,200", "(D) 20,300"], c: "(A) ₹20,600" },
            { q: "9. Choose the odd one:", o: ["(A) Premium method", "(B) Revaluation method", "(C) Without raising goodwill account", "(D) Revaluation of unrecorded asset"], c: "(D) Revaluation of unrecorded asset" },
            { q: "10. Operating lease is a", o: ["(A) Revocable Contract", "(B) Non-Revocable Contract", "(C) Operating Contract", "(D) None of the above"], c: "(A) Revocable Contract" },
            { q: "11. State which of the following statement is false:", o: ["(A) Salvage of stock means stock saved during accident", "(B) Unusual items and defective items are separate under insurance claim", "(C) Defective items means goods which cannot fetch the usual rate of gross profit", "(D) Average clause is applicable in case of under insurance"], c: "(B) Unusual items and defective items are separate under insurance claim" },
            { q: "12. A, B and C are three Partners sharing profits and losses in the ratio of 3:2:1. B retires from the firm. What is the gaining ratio of the remaining partner?", o: ["(A) 3:1", "(B) 1:2", "(C) 2:1", "(D) 1:3"], c: "(A) 3:1" },
            { q: "13. Goods are transferred from Department X to department Y at a price so as to include a profit of 33.33% on cost. If the value of closing stock of department Y is 18,000 then amount of stock reserve on closing stock will be", o: ["(A) ₹6,000", "(B) ₹4,500", "(C) ₹9,000", "(D) None of the above"], c: "(B) ₹4,500" },
            { q: "14. Income statement of a Charitable Institution is known as", o: ["(A) Profit and Loss Account", "(B) Receipts & Payments Account", "(C) Income & Expenditure A/c", "(D) Statements of Affairs"], c: "(C) Income & Expenditure A/c" },
            { q: "15. Contingent Liabilities would appear", o: ["(A) on the Liabilities Side", "(B) on the Assets Side", "(C) as a note to Balance Sheet", "(D) None of the above"], c: "(C) as a note to Balance Sheet" }
        ]
    },
    {
        setName: "December 2024",
        questions: [
            { q: "1. A Company is a going concern if", o: ["(A) its Balance Sheet shows a strong Financial Position", "(B) its Income Statement for the current year shows huge Profit", "(C) there is no evidence that it will or will have to cease operations within foreseeable future", "(D) its a Public Limited company"], c: "(C) there is no evidence that it will or will have to cease operations within foreseeable future" },
            { q: "2. Which of the following errors/omissions are not part of the Bank reconciliation process?", o: ["(A) Wrong totalling of Bank column of cash book", "(B) Wrong totalling of cash column of cash book", "(C) Posting wrong amount in Bank column of cash book", "(D) Omission to carry forward balance in the Bank column of the cash book"], c: "(B) Wrong totalling of cash column of cash book" },
            { q: "3. Which of the following is true about financial statements? (a) Financial Statements give a summary of Accounts; (b) Financial Statements can be stated as recorded facts.", o: ["(A) Statement (a) is correct", "(B) Statement (b) is correct", "(C) Both (a) and (b) are correct", "(D) None of the above"], c: "(C) Both (a) and (b) are correct" },
            { q: "4. X draws a bill on Y for ₹1,80,000 for mutual accommodation in the ratio of 2: 1. X got it discounted for ₹1,69,200 and remitted 1/3rd of the proceeds to Y. How much money should be remitted by X to Y at the time of maturity so as to enable Y to honour the bill?", o: ["(A) ₹1,20,000", "(B) ₹1,15,200", "(C) ₹1,16,800", "(D) ₹1,20,400"], c: "(A) ₹1,20,000" },
            { q: "5. A firm had a capital balance of ₹1,00,000 at the beginning of a year. At the end of the year the firm has total assets of ₹1,50,000 and total liabilities of ₹70,000. If the total withdrawals during the period is ₹30,000, what was the amount of net profit/ net loss for the year?", o: ["(A) ₹10,000 Profit", "(B) ₹20,000 Loss", "(C) ₹50,000 Loss", "(D) ₹10,000 Loss"], c: "(A) ₹10,000 Profit" },
            { q: "6. Depreciation charged to Income Statement 8,00,000, Depreciation u/s 32 of the Income Tax Act ₹20,00,000; unamortised Preliminary Expenditure as per Income Tax records ₹1,50,000; Corporate Tax rate is 40%. In this situation, the amount of deferred tax asset/liabilities to be created", o: ["(A) Deferred Tax Assets ₹4,20,000", "(B) Deferred Tax Liabilities ₹4,20,000", "(C) Deferred Tax Liabilities 4,80,000", "(D) Deferred Tax Assets ₹4,80,000"], c: "(B) Deferred Tax Liabilities ₹4,20,000" },
            { q: "7. Provision for doubtful debt on 1st April 2023 was 14,000. During the year 2023-24, the Bad Debts was 19,500. The Sundry Debtors on 31st March 2024 were ₹3,25,000. Provision is to be made @ 5% on debtors. If on 31st March 2024, there was additional bad debts of ₹2,500, then provision for doubtful debts will be", o: ["(A) Debited to Profit and Loss Account by ₹16,125", "(B) Debited to Profit and Loss Account by 14,125", "(C) Debited to Profit and Loss Account by ₹18,125", "(D) Debited to Profit and Loss Account by ₹2,000"], c: "(B) Debited to Profit and Loss Account by 14,125" },
            { q: "8. Cost of Machinery is ₹60,000. Useful life of the asset is 5 years. Annual Depreciation on Machine under Straight Line Method is ₹10,000. The scrap value of the Machine will be", o: ["(A) ₹60,000", "(B) ₹10,000", "(C) ₹50,000", "(D) ₹70,000"], c: "(B) ₹10,000" },
            { q: "9. A company deals in 3 products X, Y and Z which are neither similar nor interchangeable. At the time of closing of its Accounts for the year 2023-24: Items Historical value (₹) X=20 Y=16 Z=8 & Net Realisable value (₹): X:14; Y:16; Z:12. What will be the value of closing stock?", o: ["(A) 44", "(B) 42", "(C) ₹38", "(D) None of the above"], c: "(C) ₹38" },
            { q: "10. In case of a club, the excess of expenditure over Income is called as", o: ["(A) Surplus", "(B) Deficit", "(C) Capital Fund", "(D) Investment in Fixed Assets"], c: "(B) Deficit" },
            { q: "11. Which of these statements is not true?", o: ["(A) Accumulated Profit and Loss, General Reserve are transferred to old partners capital accounts", "(B) If assets and liabilities are to be shown in the Balance Sheet at old value, Memorandum Revaluation account is to be opened", "(C) Profit on Revaluation is transferred to the capital account of old partners in equal ratio", "(D) A Revaluation Account is a Nominal Account"], c: "(C) Profit on Revaluation is transferred to the capital account of old partners in equal ratio" },
            { q: "12. P sends 1,000 bags to Q costing ₹400 each at an invoice price of ₹500 each. The costs incurred were: P's expenses 4,000; Q's expenses ₹1,000 (non selling) and ₹2,000 (selling); 800 bags were sold by Q. What is the value of Consignment Stock at invoice price?", o: ["(A) ₹1,01,000", "(B) ₹1,01,800", "(C) ₹1,01,400", "(D) ₹1,02,000"], c: "(A) ₹1,01,000" },
            { q: "13. X and Y entered into a joint venture to undertake the public issue of ABC Ltd. The company invited applications for allotment of 2,00,000 shares at 10 per share. The issue was subscribed to the extent of 90% and the remaining were taken by Y. They agreed to share profit and loss in the ratio of 2: 3. The shares undertaken by X and Y were subsequently sold at a premium of ₹40 per share. How many shares were undertaken by X and Y?", o: ["(A) 20,000", "(B) 25,000", "(C) 18,000", "(D) 30,000"], c: "(A) 20,000" },
            { q: "14. Match the following: List 1: (I) IND AS16, (II) AS 10, (III) AS 12, (IV) IND AS 23; List 2: (a) Qualifying assets will never include biological assets, (b) Government grants as capital contribution are specifically recognized, (c) No recognition criteria for fixed assets are laid out, (d) PPE acquired in exchange of non monetary assets is recognized at fair value.", o: ["(A) I-d, II-c, III-a, IV-b", "(B) I-c, II-d, III-b, IV-a", "(C) I-a, II-b, III-c, IV-d", "(D) I-b, II-a, III-d, IV-c"], c: "(A) I-d, II-c, III-a, IV-b" },
            { q: "15. State which of the following statements is correct.", o: ["(A) Stock Debtors System of maintaining Branch Account is used for independent branch", "(B) The buyer gets immediate possession but not ownership of the asset under Installment Payment", "(C) Unusual items and defective items are separate under insurance claims", "(D) Operation lease is a Revocable contract"], c: "(D) Operation lease is a Revocable contract" }
        ]
    },
    {
        setName: "June 2025",
        questions: [
            { q: "1. Which of the following statements is correct?", o: ["(A) Financial accounts of an enterprise are treated as evidence in the court of law", "(B) Financial statements prepared by two different accountants will always show identical results", "(C) Financial statements need not take into consideration any statutory requirements", "(D) Only credit transactions are recorded in the books of accounts"], c: "(A) Financial accounts of an enterprise are treated as evidence in the court of law" },
            { q: "2. When the closing stock is shown in the trial balance, then at the end of the accounting year, closing entry for it will be required:", o: ["(A) Closing Stock A/c Dr. To Trading A/c", "(B) Trading A/c Dr. To Closing Stock A/c", "(C) Either (A) or (B)", "(D) Entry not required"], c: "(D) Entry not required" },
            { q: "3. State which of the following transactions can be classified as foreign currency transactions:", o: ["(A) Buying or selling the goods or services priced in foreign currency", "(B) Lending or borrowing when the amount are denominated in a foreign currency", "(C) Acquisition or disposition of fixed assets denominated in foreign currency", "(D) All of the above"], c: "(D) All of the above" },
            { q: "4. Which of the following is not an accounting convention?", o: ["(A) Business entity", "(B) Disclosure", "(C) Conservatism", "(D) Materiality"], c: "(A) Business entity" },
            { q: "5. Following information in the trial balance of Rupa Dresses as on 31st March, 2025: Bad Debts 12,200, Provision for Bad and Doubtful Debts on 1.4.2024 ₹7,500, Debtors 2,00,000. If further bad debt is ₹1,800 and Rupa Dresses makes a provision for bad and doubtful debts @ 5% on Debtors, the amount of such provision to be shown in Balance Sheet as at 31st March, 2025 will be", o: ["(A) ₹9,910", "(B) ₹4,210", "(C) ₹12,000", "(D) None of the above"], c: "(A) ₹9,910" },
            { q: "6. If capital at the end of the year is ₹80,000, capital introduced during the year is 60,000, drawings for the year are ₹40,000, and loss for the year is 1,20,000, then the capital at the beginning of the year was", o: ["(A) ₹1,80,000", "(B) ₹1,60,000", "(C) ₹1,40,000", "(D) ₹20,000"], c: "(A) ₹1,80,000" },
            { q: "7. State which of the following statements is true.", o: ["(A) A joint venture has a definite life", "(B) Financial statements are not comparable", "(C) Sales book is a part of ledger", "(D) Owners Equity = Assets + Liabilities"], c: "(A) A joint venture has a definite life" },
            { q: "8. On January 1, 2025, goods costing 1,32,000 were consigned by Mr. Rana of Chennai to his agent Mr. Dhana in Amritsar at a proforma invoice price of 20% above cost. Mr. Rana paid freight charges 4,000. The consignee was paid ₹2,000 per annum towards establishment cost. Mr. Dhana paid ₹1,000 as godown rent for 3 months ended 31st March 2025. 3/4th of goods were sold at 33% profit on cost. The value of unsold stock (invoice price) as on 31st March, 2025 is", o: ["(A) ₹66,000", "(B) ₹162,400", "(C) ₹1,54,400", "(D) ₹40,600"], c: "(D) ₹40,600" },
            { q: "9. Rekha draws a BOE on Reba ₹20,000 payable in 3 months. On the due date Reba could not make the payment and Reba got it notified from the notary public on payment of noting charges ₹100. Reba requested Rekha to draw a fresh bill for another three months at 12% interest. The amount of fresh bill be", o: ["(A) ₹20,700", "(B) ₹20,703", "(C) ₹20,600", "(D) 21,000"], c: "(B) ₹20,703" },
            { q: "10. State which of the following statements is not true relating to AS 10:", o: ["(A) Excludes the accounting for real estate developers", "(B) No recognition criteria for fixed assets are laid out", "(C) Recognises the revaluation of fixed assets", "(D) Does not deal with jointly owned assets"], c: "(D) Does not deal with jointly owned assets" },
            { q: "11. B & C entered into a joint venture for export of Indian handicraft goods to overseas customers. B sent goods worth ₹2,00,000 to C for export to the U.S.A. C exported goods worth ₹1,75,000 to U.S.A. for ₹2,10,000 and agreed to take away the remaining stock at the same gross profit rate as in the other exports. The goods will be valued at", o: ["(A) ₹25,000", "(B) ₹30,000", "(C) ₹22,500", "(D) 27,500"], c: "(B) ₹30,000" },
            { q: "12. State which of the following statements is true.", o: ["(A) The buyer gets immediate possession but not ownership under installment payment system on signing of contract", "(B) A marine insurance policy is taken to cover the claim for loss", "(C) For independent branch, incorporation of branch trial balance is required", "(D) Short-term lease which is often cancellable is known as Leverage lease"], c: "(C) For independent branch, incorporation of branch trial balance is required" },
            { q: "13. Assertion (A): Goodwill is an intangible asset but not a fictitious asset. Reason (R): Goodwill does not have any physical existence. Fictitious assets are not realisable whereas goodwill can be purchased or sold. Choose the correct option:", o: ["(A) Both Assertion and Reason are not correct", "(B) Reason is correct but Assertion is not correct", "(C) Assertion and Reason both are correct but Reason is not the correct explanation of Assertion", "(D) Assertion and Reason both are correct and Reason is the correct explanation of Assertion"], c: "(D) Assertion and Reason both are correct and Reason is the correct explanation of Assertion" },
            { q: "14. D, E, F are partners in a firm sharing profits in the ratio of 1:1:1. They decided to share profits in the ratio 2:3:5. The goodwill of the firm was valued at ₹1,80,000. F's Capital Account will be", o: ["(A) credited by 24,000", "(B) credited by ₹6,000", "(C) credited by ₹60,000", "(D) debited by ₹30,000"], c: "(D) debited by ₹30,000" },
            { q: "15. Mr. Ranabir is admitted into partnership for 1½ share of profit. The total capital of the old partners stood at ₹45,000 after adjustments of goodwill, revaluation of fixed assets and liabilities and transfer of reserves. Questions: 1. What amount should be brought in by the new partner as his share of capital at the time of admission? 2. If Mr. Ranabir brings 20,000 as capital for 1½ share of profits and the partners decide to adjust their capital in accordance with their profit-sharing ratio, what should be the total capital of the firm?", o: ["(A) ₹15,000, ₹80,000", "(B) ₹11,250, ₹65,000", "(C) ₹12,250, ₹56,000", "(D) ₹10,000, ₹60,000"], c: "(A) ₹15,000, ₹80,000" }
        ]
    }
];
